### ISSUE TITLE
Browser Back Doesn't Work Consistently

### ISSUE THREAD

**Issue by marrf** [pegasystems/uplus-wss#1]
**Describe the bug**
While navigating the site the browser back button frequently doesn't return to the previous page view, e.g., returning to the index.html page after authentication.

**To Reproduce**
1. Go to 'https://pegasystems.github.io/uplus-wss/'
2. Click on 'Government' (navigate to 'https://pegasystems.github.io/uplus-wss/gov/index.html')
3. Click on Login and complete the authentication dialog; now viewing the Accounts panel
4. Click on the Request Service (or any) quick link
5. Click the Browser Back
6. ...returns to 'https://pegasystems.github.io/uplus-wss/'

**Expected behavior**
Expected it to return to the U+Gov page unauthenticated view, .e.g. , 'https://pegasystems.github.io/uplus-wss/gov/index.html' with the 'Education: learn more', etc. bubbles.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 73.0.3683.103 (Official Build) (64-bit)

**Comment by ricmars** [comment]
browser back is currently not implemented when navigating inside the main portal - to go back to the account page, you need to click on the u+ logo.

**Comment by ricmars** [comment]
no plan to address this enhancement right now.

**Comment by ricmars** [comment]
some enhancements around browser back support are now available
