### ISSUE TITLE
Account Number and ContactID are not passed in Bot iframe source

### ISSUE THREAD

**Issue by PreethiBalakrishna** [pegasystems/uplus-wss#100]
Iframe source for chat bot doesnot have account number and contactID parameters in github.
src="https://crmfsdev.pega.com/prweb/PRChat/app/PegaCSFSSelfService_6378/!CSAdvisor?pyActivity=%40baseclass.doUIAction&action=createNewWork&isWebMashup=true&className=Work-Channel-Chat&flowName=pyStartCase&CustomerURL=pegasystems.github.io%2Fuplus-wss%2Fcommercial_bank%2Findex.html&Language=en-US&channelId=bot29c5e45fe9d148c6a2ece50fe6c14fbb&HelpConfigurationName=Commercial84Bot" 

whereas when we run on a local copy of github, we are seeing the values being present like below.
<iframe name="OnlineHelpIfr" allow="geolocation *;" id="OnlineHelpIfr" width="100%" height="100%" border="0" frameborder="0" src="https://crmfsdev.pega.com/prweb/PRChat/app/PegaCSFSSelfService_6378/!CSAdvisor?pyActivity=%40baseclass.doUIAction&amp;action=createNewWork&amp;isWebMashup=true&amp;className=Work-Channel-Chat&amp;flowName=pyStartCase&amp;HelpConfigurationName=Commercial84Bot&amp**;ContactId=1111111013&amp;channelId=bot29c5e45fe9d148c6a2ece50fe6c14fbb&amp;AccountNumber=72000000&amp;username=donnashelton918%40gmail.com**&amp;CustomerURL=10.225.93.98%3A9080%2FUplus%2Fcommercial_bank%2Faccount&amp;Language=en-US" style="overflow: auto;"></iframe>

in the local github we are setting these values in cookie in PegaHelperExtension.js file
/* Set cookies. To be overwritten locally */
  setCookie("ContactID", "1111111013", 30);
  setCookie("AccountNumber","72000000", 30);
  setCookie("UserName","Donna Shelton", 30); 
 
Can you please help us check why the parameters are absent when run through github?

**Comment by ricmars** [comment]
when you use a local copy of github, cookies between pega Marketing and the uplus site are shared because they are the same site and same url - as such it is possible for the uplus site to access the cookies and update them

When uplus is running on a different host - which is the expected configuration - there is no way to access the cookies used by Pega Marketing.

**Comment by ricmars** [comment]
the parameters set on the user in Uplus will be passed to the Chat bot mashup after login

**Comment by PreethiBalakrishna** [comment]
![image](https://user-images.githubusercontent.com/57181621/67954367-d8e6df80-fc16-11e9-9ad8-06724a1ee5ee.png)

I have attached the settings on user tab.
This issue is present even though user tab has the details configured. These parameters are not passed in the iframe src as described in the description.

Can you please check it and re-open if it is valid?

**Comment by ricmars** [comment]
I made some further changes on Friday - The latest Pega Chatbot JS file is now used and apparently the accountID and ContactID were not passed to the ChatBot-  did you retest with the latest Uplus app and confirm it works now.

**Comment by PreethiBalakrishna** [comment]
yes its working fine now. 
Thank you
