### ISSUE TITLE
Screen getting collapsed on double click of screen's header

### ISSUE THREAD

**Issue by Durga-Asrith** [pegasystems/uplus-wss#101]
**Describe the bug**
When working with screenflow in Web Self Service Portal desktop view on double click of any screen/step/assignment header then corresponding complete screen/assignment/step is getting collapsed.

**To Reproduce**
When working with screenflow in Web Self Service Portal desktop view 
1. Open any casetype having screenflow in it.
2. Now double click on Assignment/Screen header then the complete screen is getting collapsed.
3. After the screen getting collapsed again the screen is not getting expanded on any further actions.

**Expected behavior**
Only on single click on the screen's header the entire screen should get collapsed but should not get collapsed on double click.

**Screenshots of bug**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/57248187/68022281-e6a96d00-fcc9-11e9-8dbf-a63041ac840b.png">

On double click the issue observed 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/57248187/68022404-39832480-fcca-11e9-9325-8823c023ac4b.png">

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome, Firefox]

**Smartphone (please complete the following information):**
 -The above issue is not observed in mobile devices

**Additional context**
Please let me know in case if any further information required.

**Comment by Durga-Asrith** [comment]
<img width="960" alt="Bug Screenshot-1" src="https://user-images.githubusercontent.com/57248187/68022605-d3e36800-fcca-11e9-9127-e587a17dfb5b.png">
<img width="960" alt="Bug-Screenshot-2" src="https://user-images.githubusercontent.com/57248187/68022614-db0a7600-fcca-11e9-90b9-566dd62cb8e5.png">

**Comment by ricmars** [comment]
this is a Clarity issue - not a Uplus issue.

**Comment by ricmars** [comment]
closing issue - created BUG-521414
