### ISSUE TITLE
Text edit - payer home screen

### ISSUE THREAD

**Issue by AdamGGross** [pegasystems/uplus-wss#102]
We need to change the text on this screen.  Is this something the CSHC dev team can do ourselves?

"View my cards" --> "View my card"
"Always have access to your policy and cards..." --> "Always have access to your policy and ID card..."

![mss_home_page_nov_5](https://user-images.githubusercontent.com/55243434/68215896-0680af80-ffae-11e9-929e-365797c2bcde.png)

**Comment by ricmars** [comment]
anyone should be able to make changes and submit a pull request - this is the main reason why the code source is available on github. The file that contains all the text string is public/health_payer/i18n/lang-en.js

**Comment by ricmars** [comment]
fix merged - here is an example of the commit https://github.com/pegasystems/uplus-wss/commit/1adc27c2f1c020c1f4939522c0f09c860ee28822 

The file to update is https://github.com/pegasystems/uplus-wss/blob/master/public/health_payer/i18n/lang-en.js
