### ISSUE TITLE
Home Hero Action is missing on Mobile

### ISSUE THREAD

**Issue by anilreddygellajigari** [pegasystems/uplus-wss#103]
**Describe the bug**
The feature **Home hero action** is missing on mobile. 

**To Reproduce**
1. Launch the WSS portal on mobile
2. Click on Settings and see "Home hero action" is missing.

**Expected behavior**
Can we have this feature enabled for mobile too?

**Comment by VidyaMenon** [comment]
We have a use case for an SKO demo to click on a link in an sms which will redirect the prospect to home hero actions screen from mobile

**Comment by ricmars** [comment]
new feature added on 11/13/2019 - settings page now allows to configure the home hero action on phone since it is now suppported
