### ISSUE TITLE
Able to launch the home hero action for mobile

### ISSUE THREAD

**Issue by anilreddygellajigari** [pegasystems/uplus-wss#104]
**Is your feature request related to a problem? Please describe.**
We have a use case to launch the service case before the user logged in to WSS portal. So for this, we have used the Home hero action feature. But this feature is not enabled for mobile. 

**Describe the solution you'd like**
Enable the home hero action for mobile

**Describe alternatives you've considered**
We are using the quick links now. But with this, it is showing that the user already logged in.

**Comment by ricmars** [comment]
new feature added on 11/13/2019

added support for direct link to the hero page using the url ..../heroaction (for example https://pegasystems.github.io/uplus-wss/retail_bank/heroaction). This url also works on the phone application.
added support for the 3rd navigation item on the phone home page (right hand side) - the button will now directly go to the hero action. This functionality can be used open a mashup unauthenticated.
