### ISSUE TITLE
On Browser Refresh 404 error

### ISSUE THREAD

**Issue by anilreddygellajigari** [pegasystems/uplus-wss#105]
**Describe the bug**
When we refresh the WSS screen after login, the server responded with a status of 404 error.

**To Reproduce**
1. launch WSS portal.'
2. Login with any demo user
3. Refresh the browser

**Screenshots**
![image](https://user-images.githubusercontent.com/54167386/68589076-05b9b300-04b1-11ea-89c9-5d148933aad3.png)

**Comment by ricmars** [comment]
this is clear from the error that you are not using the github web site to run the Uplus application but instead that you are running on your local tomcat server.

**Comment by ricmars** [comment]
works fine on https://pegasystems.github.io/uplus-wss

**Comment by ricmars** [comment]
This is specific to your setup which is running the uplus application outside of the hosted environment on github.
 
You need to configure your tomcat server to use the 404.html file that is present in the root directory is the url is not found
 
![image](https://user-images.githubusercontent.com/29442140/68786024-0e270080-060d-11ea-9168-16e619aac46d.png)
The 404 page is present in the docs folder
![image](https://user-images.githubusercontent.com/29442140/68786038-197a2c00-060d-11ea-9ffa-e37b452694e1.png)
