### ISSUE TITLE
Not a customer WSS use case

### ISSUE THREAD

**Issue by abanand11** [pegasystems/uplus-wss#108]
We have below requirements in WSS for CRM Hz 8.3. Since we are using Comms as vertical, so this change has to be made in Comms WSS or can be extended for all the verticals.
1.	We need a link below the login button on index page.
2.	The label of the link can be configurable. [So for other use case we can change it as well]
3.	By default this link should be hidden. And there should be an option to enable/unhide it. [As it will not impact Comms use cases.]
4.	On click of the link, it should run a case (Similar functionality as “personalize now” button click). Again this case should be configurable.

The link is expected to be used to register a user through a Mashup.

Currently all configuration related to WSS are done through “config-settings.js”. Above requirements/configurations can be done here?

Contact person - Abhishek Anand,Brian Long 
![WSS_Not_a_Customer](https://user-images.githubusercontent.com/53535521/70298359-6a013580-1817-11ea-91f5-bbb82a5cfa4d.png)

**Comment by abanand11** [comment]
@ricmars - Hi Richard, are we planning to take this enhancement?

**Comment by ricmars** [comment]
closing this enhancement request - there are better OOTB functionality to support this use case and it is not needed to add this enhancement to the U+ site
