### ISSUE TITLE
Customer ID not getting set when invoking microsite

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#109]
In previous GitHub versions, when invoking a microsite case on clicking learn more from an offer, after logging in, the customer id used to get set to URL parameter named C. But in latest version, Customer ID is not getting set. https://fsretail84-dev.pegatsdemo.com/uplus-wss/retail_bank/. Login as Mary Romano. Click on learn more on the offer. I am having to hardcode the customer ID in the click through URL which was not the case earlier. It used to dynamically set the customer ID.

**Comment by ricmars** [comment]
closing the issue - the parameter set on the user settings are correctly sent including the CutomerID
