### ISSUE TITLE
Request to change the HELP text to a Search icon in U+ WSS portal for DemoXInsurance

### ISSUE THREAD

**Issue by YashoDeepthiPega** [pegasystems/uplus-wss#112]
The HELP text displayed in U+ WSS portal can be modified to display a 'Search' icon for better readability and also to avoid any confusion with 'Need help?' text displayed for 'Chatbot'.

Site URL: https://ins84dev.pegatsdemo.com/uplus-wss/docs/insurance

Team: DemoXInsuarance
![help](https://user-images.githubusercontent.com/59999924/72610450-65b75480-394d-11ea-8a0d-ace175f9d7cd.png)

**Comment by ricmars** [comment]
Decided to keep as is - no change
