### ISSUE TITLE
Contact Us link on WSS for Insurance

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#113]
Can we have a new link on top of the WSS page for Insurance with the label 'Contact Us'.  With this change, can we replace 'About us' to 'About'. On click of Contact Us, we would like to see an html in the format attached. If the html cannot be provided as part of GitHub code, can we provide you with the html that can be included? Kelly Cross our UX designer suggested using sidebar template format to present the data in the Contact Us html. If html here does not make sense, if we get the option to invoke a mashup, we can design the screen in the mashup as well. Thanks!
![ContactUs](https://user-images.githubusercontent.com/52248056/72872012-408e6180-3d12-11ea-9752-e01ce022e9f7.png)

**Comment by ricmars** [comment]
closing the issue -team will just use chatbot while we’re in the case.
