### ISSUE TITLE
Extra params spec to HC not getting passed to chat interaction.

### ISSUE THREAD

**Issue by AmulyaElluru** [pegasystems/uplus-wss#114]
**1. Steps to reproduce the behavior:**
1. Launch WSS portal and upload the attached JSON
2. Login with Beth Miller and click on chat bot
3. Select chat with live coordinator
4. Accept the chat on interaction portal and observe that no header, composite data is shown.

**RootCause Identified:**
Extra params specific to Health care are not getting passed from JSON and mapped to ExternalApplicationData. Problem is with extra params not getting parsed which is not applying proper context on chat initiation.

**Screenshots**
![image](https://user-images.githubusercontent.com/55691694/72880710-62ddaa80-3d25-11ea-8099-922f1ce79674.png)

![image](https://user-images.githubusercontent.com/55691694/72880720-67a25e80-3d25-11ea-8247-f40965705621.png)

![image](https://user-images.githubusercontent.com/55691694/72880746-7426b700-3d25-11ea-9c1c-db885f7e93ad.png)

**Comment by ricmars** [comment]
the issue should be fixed now - please retest and confirm
