### ISSUE TITLE
Submit and cancel buttons are truncated when modal dialog is big

### ISSUE THREAD

**Issue by Alekhyapudu** [pegasystems/uplus-wss#115]
**Describe the bug**
Submit and cancel buttons are truncated when modal dialog is bigger than the screen from which it is launched.

**To Reproduce**
1. Go to https://pegasystems.github.io/uplus-wss/gov/index.html
2. Extract and upload below config file 
[config-text.zip](https://github.com/pegasystems/uplus-wss/files/4126527/config-text.zip)
3. Click on Learn more, Apply.
4. Give all mandatory fields and proceed the case till attaching document screen.
5. Click on Attach button, and try to attach files(more than one)
6. Now you can see that submit and cancel buttons are truncated.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/51994002/73332778-cd469b80-428d-11ea-8d55-615848104cae.png)

**Desktop (please complete the following information):**
 - Browser -  chrome

**Comment by ricmars** [comment]
1/ resave py-b2c-overrides.css into your application ruleset
2/ add the following set to avoid the modal window for moving down

.modal-align-cell {
    transform: none!important;
}

**Comment by Alekhyapudu** [comment]
It worked. Thanks Richard.

**Comment by Alekhyapudu** [comment]
It worked. Thanks Richard
