### ISSUE TITLE
Scroll issue on launching offer page in WSS

### ISSUE THREAD

**Issue by manoj279** [pegasystems/uplus-wss#116]
Launch https://pegasystems.github.io/uplus-wss/insurance/

Click on Learn more below "Travel smart"

The offer.html gets loaded it maintains the same scroll of the previous page.

Expectation: When we navigate to offer section it should display the top content of the webpage.

Reference : https://pega.box.com/s/30t4qd0mykj8tbx4gvpxs8uih0p4fuw5

**Comment by ricmars** [comment]
issue has been fixed - the page will scroll to the top on page change
