### ISSUE TITLE
Help Link: KM search for mobile

### ISSUE THREAD

**Issue by SravaniKN** [pegasystems/uplus-wss#117]
Hi Richard,
In Financial services we have a requirement to start the demo in WSS by searching the KM article from the Help. And the same demo we need to run through the mobile as well. but we don't see any help link to start KM search.

Could you help us to achieve this for Mobile?

URL  :https://fsretail84-dev2.pegatsdemo.com/uplus-wss/retail_bank/
Login as Mary.Fischer@pegatsdemo.com

Web: 
![image](https://user-images.githubusercontent.com/50488225/73643041-c8705600-4698-11ea-8945-c8b775dea3ab.png)

Mobile: 
![image](https://user-images.githubusercontent.com/50488225/73643274-34eb5500-4699-11ea-800a-bcbc4f2078f1.png)

**Comment by ricmars** [comment]
KM help is not a supported page on mobile - will need to be added

**Comment by ricmars** [comment]
the feature has been added into the application - try with the latest build on github
