### ISSUE TITLE
Ability to pass context to chatbot

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#118]
We have a requirement to show a different welcome message on clicking chat icon when a mashup case is in progress. When there is no mashup case in progress, the regular welcome message should be displayed. For this, can a function be provided where we can set a string when starting the mashup case, which we can check at the chatbot case to determine what message to show? This would be similar to pegamashupsetintent function where we set a string that then gets automatically sent in the next container call. Similar to this can we have a way of setting some string/intent that can then be passed to chatbot when we invoke it? Not sure if there is any other way to send context to chatbot currently.

**Comment by ricmars** [comment]
this will require enhancement in the Chat bot API to expose an api to receive the content of a case. Please work with the team that owns this component and once an API is exposed, the uplus app can be updated to showcase this new functionality
