### ISSUE TITLE
Close button on confirm harness

### ISSUE THREAD

**Issue by manoj279** [pegasystems/uplus-wss#12]
Describe the bug
The "Close" button on mobile and "Back to Account" button on desktop in confirm harness screen isn't closing the case.Instead it must redirect to starting screen - "What type of claim are you filing". 

Steps to reproduce:

1.Go to 'https://pegasystems.github.io/uplus-wss/'
2.Click on 'Insurance' (navigate to 'https://pegasystems.github.io/uplus-wss/insurance/index.html')
3.Click on Login and complete the authentication.
4.Click on Get Started.
5.Click on Auto Accident.
6.Complete the service case.
7.On Confirm screen close button is not working as expected.

Config file - [data (1).zip](https://github.com/pegasystems/uplus-wss/files/3191288/data.1.zip)

**Comment by ricmars** [comment]
this should be fixed if you take the latest version of the clarity theme - issue the following command in your mashup iframe parent.postMessage("pegaMashupNavigateBack",  "https://pegasystems.github.io"); and it should move back to the quick links

**Comment by ricmars** [comment]
issue should be fixed with the latest version - closing the bug
