### ISSUE TITLE
Issue with Proactive Notification

### ISSUE THREAD

**Issue by PreethiBalakrishna** [pegasystems/uplus-wss#120]
Proactive service URL is not computed properly by the system.

While testing proactive notification in CSFS dev instance, we found out that the Proactive URL is not being computed properly.

Below is the configuration in self-service config portal for RetailBot

![image](https://user-images.githubusercontent.com/57181621/74126939-3e2b7300-4bff-11ea-8088-22c9fa80f780.png)
 Proactive URL is:
![image](https://user-images.githubusercontent.com/57181621/74126958-484d7180-4bff-11ea-891d-2854b706bc87.png)
https://crmfsdev.pega.com/prweb/PRRestService/CSSelfServiceNBA/V1/Container

But due to default value in the PegaHelper.js code (line:11) for port (as 80), the proactive URL is computed as below:
"https://crmfsdev.pega.com:80/prweb/PRRestService/CSSelfServiceNBA/V1/Container"
and thus proactive notifications are not working.

Below is the image of console logs:
![image](https://user-images.githubusercontent.com/57181621/74127169-d6295c80-4bff-11ea-84dd-8af406f072f3.png)

**Comment by ricmars** [comment]
issue has been fixed - the port 80 will not longer be added when the port number is not specified in the Pega Marketing setting page. if using default ports, you just need to provide the url - for example http://hostname or https://hostname. If you are not using default ports, you can specify it through the port value
