### ISSUE TITLE
Deeplinking is not working when click through email

### ISSUE THREAD

**Issue by roshinduja** [pegasystems/uplus-wss#121]
. Steps to reproduce the behavior:

1. Launch WSS portal and upload the attached JSON and save
2. Login to the respective email on which link has been sent
3. Hit on the click and observe that deep linking is not working - That is service case is expected to be launched however blank screen is shown, as in the scrn#2.

![image](https://user-images.githubusercontent.com/38033432/74175457-e7a05200-4c5b-11ea-822b-2d7a35d6c5a0.png)

![image](https://user-images.githubusercontent.com/38033432/74175707-5c738c00-4c5c-11ea-80f3-99b3bf07e957.png)

**Comment by ricmars** [comment]
issue is only seen intermittently and due to slow network where the JS for Mashup is not yet loaded. Made a fix that addresses most of the issues
