### ISSUE TITLE
AccountNumber missing in request for Proactive Notification 

### ISSUE THREAD

**Issue by PreethiBalakrishna** [pegasystems/uplus-wss#122]
AccountNumber needs to be passed while sending request for proactive notification.

File - PegaHelperExtension.js
line - 69
xhttp.send('{"CustomerID" : "'+PegaCSWSS.ContactID+'", "ContainerName" : "PrioritizeOffer", "Channel": "CallCenter"}');

Since the decision table uses both ContactID and AccountNumber to return the Flow to be run by the proactive feature, it is mandatory to pass AccountNumber in the request.
![image](https://user-images.githubusercontent.com/57181621/74525282-b7500080-4f46-11ea-8880-0d265092285f.png)

Since multiple verticals are using this feature, we may end up in adding more parameters to the request later.
Can we get an extension to pass extra parameters to the request as well?

**Comment by ricmars** [comment]
we are now passing the Account ID, Contact ID and extra parameters to the http request 
![image](https://user-images.githubusercontent.com/29442140/74561564-cdee5b80-4f36-11ea-9edc-3f03c4de9f7e.png)


![image](https://user-images.githubusercontent.com/29442140/74561516-b1522380-4f36-11ea-91e0-290b04022290.png)
