### ISSUE TITLE
Logout does not invalidate chat session

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#123]
If I login as a certain user and chat with bot, then logout and login as another user and start chat again, I can see the earlier persons chat. Logout should invalidate the existing chat session.

**Comment by ricmars** [comment]
did you check the checkbox 'reset chat when user logs out'

![image](https://user-images.githubusercontent.com/29442140/75040331-785f0500-5488-11ea-9851-9a74ef646358.png)

**Comment by VidyaMenon** [comment]
Have not done that Richard. Looks like we need latest code in our instance.
Do not see this checkbox in my settings file.
