### ISSUE TITLE
Modifications to mobile screens for Insurance

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#125]
Can we have the 3 options/icons available on mobile to be renamed to Policies, Self Service and Recent Activity (Currently they are Get a quote, File a Claim and Support request) and have appropriate icons to suit the labels. When clicking on the middle icon, we get to a screen. We would like that heading to state 'Options for Self Service'. 

Can we make the third icon inactive so that nothing happens on click. Currently it takes us to a dummy screen.
Can we make the first icon click show a section with only policies and remove the 'to do' and 'quick links' and offer. Or provide an option in settings file where this can be configured.

**Comment by ricmars** [comment]
Can we have the 3 options/icons available on mobile to be renamed to Policies, Self Service and Recent Activity- **Done**
have appropriate icons to suit the labels. **Done** - if not good, create pull request
We would like that heading to state 'Options for Self Service'. **Done**
Can we make the third icon inactive so that nothing happens on click. **Done**

Can we make the first icon click show a section with only policies - not done - policies is hardcoded - why hide the todo on this screen?

**Comment by ricmars** [comment]
removed offer and quicklink for the 1st link on phone for insurance only -
closing enhancement request.

**Comment by VidyaMenon** [comment]
Hi @ricmars 
This change seems to have broken quick links. Now when I login to mobile and click Self Service icon (middle one), I see the 3 quick links (non hidden ones) which is correct. But when I click Address Change, I just see a blank screen. The case is not getting invoked. When I try the same with wss code before this change, it is working fine. 

json file is given below. 


{"i18n":{"defaultlocale":"en","languages":["en"],"showLangSwitch":false},"quicklinks":[{"title":{"en":"Auto accident"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-FNOL-Auto-Pers","url":"https://ins84demodata.pegatsdemo.com/prweb","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-car-solid","extraparam":"","hide":false},{"title":{"en":"Homeowner"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-Personal-HomeOwner","url":"https://ins84demodata.pegatsdemo.com/prweb","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-car-solid","extraparam":"","hide":true},{"title":{"en":"Resume Address Change"},"action":"openAssignment","actionparam":"","objclass":"PegaIns-Serv-Work-ChangeAddress","url":"https://ins84demodata.pegatsdemo.com/prweb/app/CSISelfService_9215/","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-car-solid","extraparam":"","hide":true},{"title":{"en":"Change address"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-ChangeAddress","url":"https://ins84demodata.pegatsdemo.com/prweb","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-home-alt-solid","extraparam":"IsWSSQuickLink=true,IsWSSCACase=true","hide":false},{"title":{"en":"Make payment"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-MakePayment","url":"https://ins84demodata.pegatsdemo.com/prweb","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-life-ring-solid","extraparam":"","hide":false},{"title":{"en":"Change beneficiary"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-Life-ChangeBeneficiary","url":"https://ins84demodata.pegatsdemo.com/prweb","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-plane-solid","extraparam":"","hide":true}],"billpay":{"action":"createNewWork","actionparam":"","objclass":"","url":"","startcase":"pyStartCase","application":"","extraparam":"","hidebillpay":false},"todo":{"action":"display","actionparam":"WSSHomeScreenMain","objclass":"Data-Portal","url":"https://ins84demodata.pegatsdemo.com/prweb","startcase":"pyStartCase","application":"CSISelfService","extraparam":"","hideactivity":true,"hideaccount":false},"kmhelp":{"action":"display","actionparam":"KMHelpSitePortal","objclass":"Data-Portal","url":"https://ins84demodata.pegatsdemo.com/prweb","startcase":"pyStartCase","application":"CSISelfService","extraparam":"pyActivity=KMDisplayHelpPortal,KMHelpSiteName=UPlusHelp","username":"","password":""},"homeheroaction":{"action":"createNewWork","actionparam":"","objclass":"","url":"","startcase":"pyStartCase","application":"","pega_userid":"","pega_pwd":"","extraparam":""},"offeraction":{"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-MicroIns-Travel","url":"https://ins84demodata.pegatsdemo.com/prweb","startcase":"pyStartCase","application":"CSISelfService","pega_userid":"MaryJohnson86@pegatsdemo.com","pega_pwd":"install12345!","extraparam":"ContactId:CONT-28"},"users":[{"username":"Geoff.Smith","password":"install12345!","img":"Avatar-Geoff.jpg","company_name":"","name":"","accountID":"","contactID":"CONT-11","customerID":"","extraparam":"","pega_userid":"Geoff.Smith@pegatsdemo.com","pega_pwd":"install12345!","bill_pay":164.8,"load_by_default":false,"billpay":164.8},{"username":"MaryJohnson","password":"install12345!","img":"avatar-maryjohnson.jpg","company_name":"","name":"","accountID":"","contactID":"CONT-28","customerID":"PEGAINSCRM-WORK-CONTACT CON-2307","extraparam":"","pega_userid":"MaryJohnson86@pegatsdemo.com","pega_pwd":"install12345!","bill_pay":164.8,"load_by_default":true,"billpay":164.8},{"username":"Ava.Jensen","password":"install12345!","img":"Avatar-Eva.jpg","company_name":"","name":"","accountID":"","contactID":"CONT-10209","customerID":"PEGAINSCRM-WORK-CONTACT CON-24001","extraparam":"","pega_userid":"Ava.Jensen@pegatsdemo.com","pega_pwd":"install12345!","bill_pay":164.8,"load_by_default":true,"billpay":164.8}],"pega_chat":{"WCBConfigName":"CSIWSS web chat bot","WebChatBotID":"bota0fd61dc4b054ea899e9f943ab454d94","ApplicationName":"CSISelfService","MashupURL":"https://ins84demodata.pegatsdemo.com/prweb/PRChat/app/CSISelfService_7312","ShowAsButton":true,"EnableProActiveNotification":false,"ResetLogout":true,"ProActiveNotificationDismissTime":"","CoBrowseServerURL":"https://ins84demodata.pegatsdemo.com:8043/co","CoBrowseToken":"58d3c9aa21365a993bb0fed3"},"pega_marketing":{"Host":"ins84demodata.pegatsdemo.com","Port":"8043","replaceHomePageHeader":false,"showAIOverlay":false,"enableRTS":false,"homePage":{"containerName":"TopOffers","placement":"Hero,Tile,Tile,Tile","clickaction":"Mashup"},"accountPage":{"containerName":"Progressive","placement":"Tile","clickaction":"Mashup"},"phonePage":{"containerName":"TopOffers","placement":"Tile","clickaction":"Mashup"},"offerPage":{"containerName":"TopOffers","placement":"Hero,Tile,Tile,Tile","clickaction":"Mashup"}}}

**Comment by ricmars** [comment]
likely a configuration issue - wrong files on the server or wrong config file
auto-accident works fine for me using the above configuration

![image](https://user-images.githubusercontent.com/29442140/76630599-af1fbc80-6516-11ea-95ac-4483800c2033.png)

**Comment by VidyaMenon** [comment]
Auto accident seems to be working because it is the first one in quick
links list so resolves to quicklink 0. But address change is actually
quicklink3, but from mobile it is resolving as quicklink 1 which is
homeowners and not correctly configured. Shouldn't it consider the auto
hide and ignore the second item in quicklinks and resolve to quicklink 3
for address change instead of quicklink 1? Currently we changed the order
in quicklinks and resolved the issue, but I think this is a bug?

**Comment by ricmars** [comment]
because of the filtering I added on mobile to hide quicklinks, the wrong object was being opened - this issue is fixed with my last commit
