### ISSUE TITLE
Unable to access offer.html on local WSS

### ISSUE THREAD

**Issue by satyast** [pegasystems/uplus-wss#128]
Problem statement
Unable to access the offer.html on local WSS

We are running the WSS locally for our healthcare instance. One of the demo scenarios hits the following url,

https://e2ehc84-product-data.pegatsdemo.com/uplus-wss/health_payer/offer.html?MemberID=MB2015072423&ProgramName=Prediabetes&Channel=WSS&CustomerEntityID=SAHC-SAMPLE-WORK-CONTACT%20SAHCCON-80016

This is the url that we used in earlier releases and it worked fine with uplus-wss 1.1.0, even if we ran it locally. Currently, we are experiencing issues when we run the same URL on the new uplus-wss code.

Following the wiki page, we mapped the 404.html in the web.xml. Also when we tried to hit the offer.html with the ?offerAction=1 parameter, it does not work. But the sam works with the GitHub hosted WSS.

The below is not working,
https://e2ehc84-product-data.pegatsdemo.com/uplus-wss/health_payer/offer.html?offerAction=1
but this works,
https://pegasystems.github.io/uplus-wss/health_payer/offer.html?offerAction=1

I would like to know if I am doing something wrong here. Also, i need to pass these parameters to the offer action, MemberID=MB2015072423&ProgramName=Prediabetes&Channel=WSS&CustomerEntityID=SAHC-SAMPLE-WORK-CONTACT%20SAHCCON-80016

We tried hitting the offer.html url with the above parameters in both ways, both do not work.

https://e2ehc84-product-data.pegatsdemo.com/uplus-wss/health_payer/offer.html?offerAction=1&MemberID=MB2015072423&ProgramName=Prediabetes&Channel=WSS&CustomerEntityID=SAHC-SAMPLE-WORK-CONTACT%20SAHCCON-80016

and

https://e2ehc84-product-data.pegatsdemo.com/uplus-wss/health_payer/offer.html?MemberID=MB2015072423&ProgramName=Prediabetes&Channel=WSS&CustomerEntityID=SAHC-SAMPLE-WORK-CONTACT%20SAHCCON-80016&offerAction=1

Could you please look into this and help us understand where we are going wrong.

**Comment by ricmars** [comment]
you need to setup the 404 to perform the redirect - the offer.html is no longer available in the distribution - see https://github.com/pegasystems/uplus-wss/wiki/How-to-customize-the-Uplus-application
