### ISSUE TITLE
In U+ Insurance, When looking at KM on mobile, there is a large space at the bottom that appears to be for the chat icon.  Can this be made smaller/removed as it is taking up space on the screen that has no purpose.

### ISSUE THREAD

**Issue by YashoDeepthiDemoXIns** [pegasystems/uplus-wss#137]
In U+insurance, When looking at KM(by clicking on HELP)
![IMG_943A86A8C0B8-1](https://user-images.githubusercontent.com/63443399/78970408-d7ef9d80-7b26-11ea-9999-2babdb532cd9.jpeg)
 on mobile, there is a large space at the bottom that appears to be for the chat icon.  Can this be made smaller/removed as it is taking up space on the screen that has no purpose.

**Comment by ricmars** [comment]
issue has been fixed
