### ISSUE TITLE
Chatbot spacing issue for service cases

### ISSUE THREAD

**Issue by YashoDeepthiDemoXIns** [pegasystems/uplus-wss#138]
In U+Insurance WSS portal , Upon starting a service case flow in mobile view of WSS screen, a large space is displayed at the bottom that appears to be for the chat icon.  Can this space be removed as it is taking up space on the screen that has no purpose
![IMG_8029](https://user-images.githubusercontent.com/63443399/79722407-a4202f00-8301-11ea-9927-2c16c512cd11.PNG)

Same issue has been fixed in KM articles screen recently : https://github.com/pegasystems/uplus-wss/issues/137

**Comment by ricmars** [comment]
the issue has been fixed in the latest commit - there was a hardcoded height for the offer on a phone
