### ISSUE TITLE
Mashup not getting generated consistently

### ISSUE THREAD

**Issue by manoj279** [pegasystems/uplus-wss#149]
When we login and login off continuously for 3-4 times, the mashup configuration in settings is being removed. Sometimes even though the configuration exists, the iframe is not getting generated.
We need to again upload the json file and continue.
Use case:
We display claim details information in todo widget.
We have a landing page where we can advance the status of the claim work object.
So upon status change, we will logoff and login in WSS to show the current status

**Comment by ricmars** [comment]
please reach out to me with a reproducible scenario - I am closing the issue and will reopen once we have a reproducible scenario. logout / logout should not wipe out the configuration stored in the local storage of your browser.
