### ISSUE TITLE
State of the deeplink is not cleaning up when navigating back

### ISSUE THREAD

**Issue by sai1231** [pegasystems/uplus-wss#151]
We are using quicklink deeplink url to directly open an assignment. During this process when we click on Home/Back to account, the To do Component(mashup) has to be displayed on homepage but its trying to load the quicklink instead of todo mashup.
Looks like the parameters passed in the quicklink url are used in the todo mashup and thats why its trying to open the quicklink.
However the todo mashup works fine when the user logs off and re-login.

**Comment by ricmars** [comment]
the state of the deeplink was not reset - this is now fixed with the latest commit - the deeplink state is reset once the mashup that uses the deeplink settings is rendered.
