### ISSUE TITLE
Issue with TabbedScreenflow7 harness

### ISSUE THREAD

**Issue by subhamhitk9940** [pegasystems/uplus-wss#155]
The bubbles that show the steps in the screenflow on top seem to display fine in B2C portal. But from github, those are missing. Had to override pyB2CActionArea section and remove the highlighted when condition to get it visible.
![7298648c-59fa-40b4-a0e4-1b3d4fe33d86](https://user-images.githubusercontent.com/78339961/106422977-8c2b2d80-6485-11eb-9640-2c84f682348d.PNG)

**Comment by ricmars** [comment]
no plan to fix - override section from clarity theme
