### ISSUE TITLE
chatbot is not loading

### ISSUE THREAD

**Issue by abhishekchepyala** [pegasystems/uplus-wss#156]
**Describe the bug**
Chatbot is not loading after auto login with the below URL
https://e2ecommsdeval.pegatsdemo.com/uplus-wss/comms/index.html?pega_userid=DianaPrince

**To Reproduce**
1. Auto login using the URL  https://e2ecommsdeval.pegatsdemo.com/uplus-wss/comms/index.html?pega_userid=DianaPrince
2. Click on chat icon, it is not loading

**Expected behavior**
Chat should be working in the user context

**Screenshots**
chat is not loading
![image](https://user-images.githubusercontent.com/50229449/114172984-08ddfa80-9954-11eb-9af9-a778d7291e40.png)
console
![image](https://user-images.githubusercontent.com/50229449/114173163-52c6e080-9954-11eb-9304-ba12d65635ef.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 
**Additional context**
The chat is working on the home screen and also with manual login

**Comment by ricmars** [comment]
issue is due to dependency of loading mashup for todo and Pega Mashup - made a fix to only load one mashup - seems to be working - closing the bug
