### ISSUE TITLE
Request for the menu options for display message instead of a static text.

### ISSUE THREAD

**Issue by AiswaryaSkandamani** [pegasystems/uplus-wss#157]
**Is your feature request related to a problem? Please describe.**
When the Digital messaging channel web chatbot is initiated the display text option available is only a statement. Can we by default provide menu options like how it was available for legacy web chat instead of a static display message.

**Describe the solution you'd like**
Availablity of menu options as soon as the chat icon is chosen

**Describe alternatives you've considered**

**Additional context**
<img width="221" alt="issue pega wss" src="https://user-images.githubusercontent.com/25148350/114394684-1c3dcf80-9bb9-11eb-974b-de2f45cc54dc.PNG">

**Comment by ricmars** [comment]
this is a feature enhancement for the DMM - not for uplus
the new Web Messaging does not ping CS when the widget loads, and UME needed the display/welcome message functionality as well, so the display message configuration was built into the DMM (Digital Messaging Manager). As a result, it is currently text only.

In 8.7, we are building a configurations database into the Digital Messaging Service, so we will be able to have more complex welcome messages configured in CS, have that configuration pushed to the config database, and be able to use it without having to make a call to CS when the widget loads.
