### ISSUE TITLE
Citizen Engagement : Weird movement of the Contact Form within the chatbot

### ISSUE THREAD

**Issue by AbdurRahman311** [pegasystems/uplus-wss#159]
Issue 1:

Open the link https://e2epgpdevamzlnx85.pegatsdemo.com/uplus-wss/gov or https://e2epgpamzlnx85-qa.pegatsdemo.com/uplus-wss/gov/index.html

click on chat icon

Navigate till Fill out form

Click on Fill out Form

Fill the info

Click on Contact information Fill out form

After clicking on flash icon to prefill data, the window is moving to top

Kindly refer the attached document for the screenshots

[BUG-628748.docx](https://github.com/pegasystems/uplus-wss/files/6324287/BUG-628748.docx)

Kindly refer the bug BUG-628748 for your reference

**Comment by AbdurRahman311** [comment]
I request you to kindly provide an update on the above

**Comment by ricmars** [comment]
this issue is not related to uplus - it is a Pega platform chatbox issue - on clicking on the flash icon, the modal dialog used inside the chat bot is redrawn and pushed to the top
