### ISSUE TITLE
Citizen Demo(WSS) : Delete Icon misleading

### ISSUE THREAD

**Issue by AbdurRahman311** [pegasystems/uplus-wss#160]
**Issue :** The delete Icon on the contact form of the Citizen Demo in the chatbot is misleading

**Steps to reproduce :**
Open the link https://e2epgpdevamzlnx85.pegatsdemo.com/uplus-wss/gov or https://e2epgpamzlnx85-qa.pegatsdemo.com/uplus-wss/gov/

click on chat icon

Navigate till Fill out form

Click on Fill out Form

Click on Contact details Fill out form and fill information

Click on Attach now

Attach the ID proof

Click on Attach

Kindly refer BUG-645959 for your reference

Observe the delete icon after it is attached , it is looking like box rather than delete icon

![image](https://user-images.githubusercontent.com/82648766/115348088-d217a800-a1cf-11eb-9a18-14b7e514ab8e.png)

**Comment by AbdurRahman311** [comment]
Could you please Kindly provide me an update on the above

**Comment by ricmars** [comment]
issue is unrelated to uplus - this an issue with Pega chat
