### ISSUE TITLE
Navigation of back and forth steps is not working when prod level 5

### ISSUE THREAD

**Issue by DEVUS1** [pegasystems/uplus-wss#161]
Issue : Navigation of back and forth steps in a screen flow is not working when pyBlockUnregisteredRequests is enabled (production level is set to 5).

To reproduce :
Launch any case type with screen flow.
Complete few stages in the flow and navigate to previous steps.
Observe that the screen is not navigated and a 403 status error is returned when network calls are traced.
![WSS issue](https://user-images.githubusercontent.com/83219872/116077263-e87fa100-a6b2-11eb-8d4e-4242cca1a9c3.jpg)

Expected : Screen should be navigated to the previous step selected.

Issue reproducible in : lab0573.lab.pega.com/wss/retail_bank
Attached the json file for config.

[configfile lab0573.txt](https://github.com/pegasystems/uplus-wss/files/6382790/configfile.lab0573.txt)

**Comment by ricmars** [comment]
issue is unrelated to uplus - this an issue with the Pega Platform.
