### ISSUE TITLE
WSS Issue : Incorrect display of 'Login' button(It is a single word and no space is required) in WSS portal

### ISSUE THREAD

**Issue by AbdurRahman311** [pegasystems/uplus-wss#163]
Issue : Top right corner of the WSS page has login button. Login is a one word, there should not be any space in it  

Steps to Reproduce : 

1. Try launching https://e2epgpqaamzlnx86.pegatsdemo.com/uplus-wss/gov_grants/index.html
2. Kindly refer the below screenshot for your reference

![image](https://user-images.githubusercontent.com/82648766/120163062-b5cb4a00-c216-11eb-9e81-e2bc076e4a0a.png)

**Comment by cw-pega** [comment]
Log in and Login are often confused — I agree that no space is correct in this example since its using **Login** as a noun. http://www.enhancemywriting.com/login-or-log-in

**Comment by cw-pega** [comment]
In this instance "Log in" is being used as a verb like "Sign in". If it was a noun, or an adjective then it should be one word. Eg. Navigate to the _login_ page, or this is my _login_. I agree in this instance it's a bit ambiguous and could be presented as a noun or a verb. http://www.enhancemywriting.com/login-or-log-in

**Comment by ricmars** [comment]
this is cosmetic and can be changed - other apps used the same word
![image](https://user-images.githubusercontent.com/29442140/120496211-63f80080-c38b-11eb-85f3-f7161b4c175f.png)

![image](https://user-images.githubusercontent.com/29442140/120496396-8853dd00-c38b-11eb-8f4d-31a8e2f1baa8.png)

**Comment by ricmars** [comment]
closing issue - there is nothing wrong with using the word 'Log in'
