### ISSUE TITLE
Wss Portal Issue : The Appearance of the 'Cancel' button is not appropriate

### ISSUE THREAD

**Issue by AbdurRahman311** [pegasystems/uplus-wss#164]
Issue : The appearance of the ‘Cancel’ button is not as expected kindly refer the below screenshot for your reference.  
 
Steps to Reproduce:
1.	Launch https://pegasystems.github.io/uplus-wss/gov url
2.	Click on ‘Apply Now’
3.	Traverse through the screens until you reach ‘Application Intake’ Screen
4.	Click on ‘+Attach’ hyperlink
5.	There you will observe the below behaviour

![image](https://user-images.githubusercontent.com/82648766/121805592-73b7f480-cc69-11eb-8952-03f8dce84fb1.png)

**Comment by ricmars** [comment]
this issue is unrelated to the uplus app - the cancel button is rendered by the Pega Platform as a Pega Mashup - check that your application is using the correct application stack (e.g. Theme-Clarity is on top) - also make sure that the button is not a legacy button in this section
