### ISSUE TITLE
Separate container requests for the offer(x) pages

### ISSUE THREAD

**Issue by lekshmipega** [pegasystems/uplus-wss#165]
**Is your feature request related to a problem? Please describe.**
Yes, even when I have configured "Offer page" settings with a new Container name, offer1/offer2/offer3/offer4 pages in retail_bank site is not picking it up. Request always goes with "TopOffers" .

**Describe the solution you'd like**
Flexibility to call different containers on those sub links on home page. It's quite a common CDH usecase to show relevant offers based on customer needs. If someone is interested in say , Credit cards, and clicks on that link, we can call specific container at the Group level in marketing (Sales/Credit cards)

**Comment by ricmars** [comment]
enhancement done - each offer has its own container setting - see https://pegasystems.github.io/uplus-wss/retail_bank
