### ISSUE TITLE
Close the work object and create new work object

### ISSUE THREAD

**Issue by kollm1** [pegasystems/uplus-wss#167]
In CLMWSS, we have a requirement where abandon journey link is visible on many screens, when user clicks on it, we are supposed to move back to home screen for creating a new case again, But on click of learn more , we are seeing the same case when Script: pegaMashupNavigateBack is used on abandon link. Not able to create a new case post click on abandon journey.

**Comment by ricmars** [comment]
in your mashup configuration under quicklink - uncheck 'Retain state on reload' - when coming back to the quicklink, a new mashup will be created

![image](https://user-images.githubusercontent.com/29442140/126823461-1aa5fecb-c12a-40d2-a2d3-df8c53653c00.png)
