### ISSUE TITLE
Quicklinks in mobile are not hidden though we hide those in settings file

### ISSUE THREAD

**Issue by YashoDeepthiDemoXIns** [pegasystems/uplus-wss#168]
We noticed that even though the quicklink is hidden in settings file. In mobile view we are still able to see the hidden quicklinks.

In Web WSS it is hidden however.
<img width="609" alt="e1f9e04f-6728-499b-bc0a-fa50dea16027" src="https://user-images.githubusercontent.com/63443399/128323975-51de9777-2ab3-4893-9e44-a0eb99faa078.PNG">
<img width="209" alt="e950eee4-65eb-40bd-a6ec-022dd170df06" src="https://user-images.githubusercontent.com/63443399/128323985-826bc10e-62d7-42aa-b447-4873f355c920.PNG">

**Comment by ricmars** [comment]
issue has been fixed
