### ISSUE TITLE
Scroll Bar for Mashup Iframe

### ISSUE THREAD

**Issue by avinay** [pegasystems/uplus-wss#17]
We are getting scroll bar for mashup iframe when though you have ample space to accommodate the mashup screen. 

The issues we see Iframe is rendered with inline height instead of 100% 

![screenshot-scrollbar-issue](https://user-images.githubusercontent.com/572447/58015176-34fdf180-7b18-11e9-893a-c3ffcf3ba38b.png)

**Comment by ricmars** [comment]
need to set https://pegasystems.github.io in the security tab of your application

**Comment by avinay** [comment]
even after updating the security tab, the issues persists. Almost all screens which has mashup content having scroll issue. 
![93723b3c-e20b-4bf6-b3be-ca7080e82a5c](https://user-images.githubusercontent.com/572447/58091121-7066f180-7be6-11e9-8647-3f80d0b7a4d7.png)
