### ISSUE TITLE
Unable to select the checkboxes displayed on the screen

### ISSUE THREAD

**Issue by arwinirahulkumar** [pegasystems/uplus-wss#172]
**Describe the bug**
Unable to select the checkboxes displayed on the screen
![image](https://user-images.githubusercontent.com/51435979/171167402-f0e7e64d-080f-41d8-bc89-3e87275961eb.png)

**To Reproduce**

1. Launch U+ portal from the https://pegasystems.github.io/uplus-wss/insurance/
2. Upload the attached config file

3. Login with Mary Johnson from login button

4. Ensure that DXAPI-v1 is configured  as Pega Platform access

5. Launch the statement copy service case from the quick links sections

**Expected behavior**
Checkbox should get selected when clicked on it.
![image](https://user-images.githubusercontent.com/51435979/171171680-e2c7214c-22b2-4376-bfb9-e54e8f1fde85.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by arwinirahulkumar** [comment]
[](url)

**Comment by ricmars** [comment]
issue has been resolved with latest update of the mashup web component - the issue was limited to checkbox in a table using the v1 api
