### ISSUE TITLE
Page instructions not expected when appending a row to table

### ISSUE THREAD

**Issue by SrideviPatibandla** [pegasystems/uplus-wss#173]
1.  Please refer to agile studio BUG-725863 for config file and login to https://pegasystems.github.io/uplus-wss/insurance/ as MaryJohnson07
2. Click on Change Beneficiary to create a case.
3. Select a policy on the first screen and click on submit.
4. In the next screen, click on add item and add details to a row.
![image](https://user-images.githubusercontent.com/106650114/171340658-1b82633d-c6ea-4375-b61d-7cdb5bd2c3da.png)

5. When we click on Add item in the above screen, a row is appended to pyWorkPage.ProcessPolicyList(1).PersonBeneficiaries(3) and to this .PersonBeneficiaries(3) page , all the properties in the table like Designation, Last name, First name, Relationship, SSN etc needs to be inserted. 

**Issue:**

When using the Uplus portal using DX v1 APIs, Page instructions are formed as below:
![image](https://user-images.githubusercontent.com/106650114/171340798-62d5ad61-1d56-45ce-bc13-9df06fc7e3b8.png)
As highlighted in red, the target must be ProcessPolicyList(1).PersonBeneficiaries(3) so that beneficiaryDesignation is added to this page list. 

**Working scenario ( in process extender for Salesforce lightning ):**
![image](https://user-images.githubusercontent.com/106650114/171340930-17ae725a-39d2-4058-a353-52361f37bbb0.png)

**Comment by ricmars** [comment]
issue has been fixed - closing the bug
