### ISSUE TITLE
pyCaseInformation is used insteadof confirm harness in Uplus with DX APIs v1

### ISSUE THREAD

**Issue by SrideviPatibandla** [pegasystems/uplus-wss#174]
**Describe the bug**
When we use Uplus portal configured to use DX v1 APIs, once all the assignments are completed while processing a case, instead of displaying confirm harness, pyCaseInformation section is displayed. This is inconsistent with mashup, react starter pack, or process extender for salesforce lightning. So, only for Uplus DX v1 APIs, an additional maintenance of the pyCaseInformation section is needed.

**To Reproduce**
.1. Please use the attached config file ( that uses v1 APIs) and login to https://pegasystems.github.io/uplus-wss/insurance/ as MaryJohnson .
2. Click on Change Beneficiary to create a case. 
3. Enter basic details and proceed to the confirmation screen.

**Expected behavior**
all other UI frameworks in marketplace like react starter pack and process extender for salesforce lightning, show confirm harness  using  https://<host>/prweb/api/v1/cases/{ID}/pages/{pageID}

![image](https://user-images.githubusercontent.com/106650114/171344287-b1623ac9-5674-44f6-b5a5-eb6a3ce24bfc.png)

**Comment by ricmars** [comment]
the mashup web uses pyCaseInformation which is a standard section in theme-cosmos or ui-kit

**Comment by ricmars** [comment]
closing issue - no action
