### ISSUE TITLE
Issues with table layout in Uplus DX API v1

### ISSUE THREAD

**Issue by SrideviPatibandla** [pegasystems/uplus-wss#175]
1. Please refer to agile bug BUG-725601 for config file and login to https://pegasystems.github.io/uplus-wss/insurance/ using MaryJohnson07.
2. Click on Change Beneficiary to create a case.

**Issue 1:** 
Observe that, this table layout is only used for selecting existing policies. So Add row/Delete row is not required.As per US-436444 , DX API should send the information if Add/Delete row buttons are required.  This data to be used to hide these actions. These changes have been made part of react starter pack latest release.
![image](https://user-images.githubusercontent.com/106650114/171345978-b9024771-2268-47d0-aaca-e3bd8305f6c6.png)

**Issue 2**
Click on submit in the change beneficiary service case. A title is displayed for all editable tables. This is not required.
![image](https://user-images.githubusercontent.com/106650114/171346078-a43c3e28-be07-49d2-9f3a-93ef441914eb.png)

**Issue 3**
As shown in the screenshot above, if there are more columns in the table, the table width is not as expected. This is working as expected in react starter pack and also in process extender for salesforce lightning.  

**Issue 4**
Delete Item button is not displayed for table layouts. In all these tables highlighted below, the Delete item option is not displayed for tables.
![image](https://user-images.githubusercontent.com/106650114/171346347-7847770b-fc21-4d32-bd07-4c0e3e3b9e71.png)

**Issue 5**
 In the same screen, let's say , click on Add item for organization. Change the dropdown value and click on add item again. Below error is observed.
![image](https://user-images.githubusercontent.com/106650114/171346624-ae9c8bbd-d350-490a-b8ee-4ecdb148cdaa.png)
![image](https://user-images.githubusercontent.com/106650114/171346677-6512de15-ad61-492e-8211-dbaacabe8e5a.png)

**Comment by ricmars** [comment]
issue 2, 3 and 5 are fixed 
issue 1 and 4 is an enhancement that does not work - even if 8.8 - it is not possible to know if a table supports add/delete
