### ISSUE TITLE
Issues in repeating dynamic layouts in UPlus using DXAPI

### ISSUE THREAD

**Issue by sukanyab0** [pegasystems/uplus-wss#176]
1.Please add the attached config file (refer BUG-726009) and login to https://pegasystems.github.io/uplus-wss/retail_bank/ using Shea Parker.
2. In todo list open any work object from Manage Customer Circumstance case.

3. We see "+Add item" getting added to RDLs and there is no config to hide the same.

![image](https://user-images.githubusercontent.com/106668674/171401169-07d1a234-98bf-469d-bfbd-ed8340e097ca.png)

**Comment by ricmars** [comment]
fixed in 8.7 - include the section with the RDL as Readonly - see demo with car insurance on v1 - review screen
