### ISSUE TITLE
Incorrect read only date format in web mashup component

### ISSUE THREAD

**Issue by sukanyab0** [pegasystems/uplus-wss#178]
Launch https://pegasystems.github.io/uplus-wss/insurance

Upload the attached config file

And save the settings

Login with Mary johnson and launch change beneficiary from quick links
![image](https://user-images.githubusercontent.com/106668674/173552903-2f4215d3-4bac-4052-ae92-722b871ed882.png)
We are getting standard format even we are getting date format in API response (Attaching API response)

![image](https://user-images.githubusercontent.com/106668674/173552927-f2e63336-f761-4ece-82bc-ff6d1e842d98.png)
Expected:
![image](https://user-images.githubusercontent.com/106668674/173553725-2d31450d-5b6a-443d-8651-44b3f8620e0d.png)

**Comment by ricmars** [comment]
issue has been fixed
