### ISSUE TITLE
Prompt values are not displayed in table layout

### ISSUE THREAD

**Issue by manoj279** [pegasystems/uplus-wss#179]
We have configured a prompt field in a table layout
![image](https://user-images.githubusercontent.com/22269847/175524449-d2859754-dd4b-427c-8b44-c2d543e6f757.png)
![image](https://user-images.githubusercontent.com/22269847/175524462-e93849c7-3637-4338-b617-2a497b3bf790.png)

While rendering the table, although the response contains data its not been displayed
![image](https://user-images.githubusercontent.com/22269847/175524630-42b0ae23-f479-4965-b370-94df5584741d.png)

Refer to BUG-730799 for instance details

**Comment by ricmars** [comment]
the issue has been fixed - The designation field is correctly populated

**Comment by ricmars** [comment]
closing issue
