### ISSUE TITLE
No config to remove work 'Case information' in confirm screen

### ISSUE THREAD

**Issue by Nagarohith** [pegasystems/uplus-wss#180]
We're using DX API to load the UI.
In confirm screen we see 'Case information' will be displayed as label as in below picture:
![image](https://user-images.githubusercontent.com/27344419/175877960-1b4cfe4b-6417-4ea3-9c2c-3062012c24dd.png)

Please refer the bug: BUG-731084 to find the instance details and config file

**Comment by ricmars** [comment]
removed the case information
