### ISSUE TITLE
Bullets configured in RTE are not displayed in WSS using DX API

### ISSUE THREAD

**Issue by Nagarohith** [pegasystems/uplus-wss#181]
We're using DX API to load the UI. 
Credentials and config file are attached at the bug BUG-731112
Issue 1:
In confirm screen we need to display what's next points as in below picture but we're not seeing Bullets in front of every line.
![image](https://user-images.githubusercontent.com/27344419/175894615-51155e5b-a5c7-4072-841e-2aa5db61599a.png)

Issue 2: 

What's next label is not displayed as heading to the points.
Section details:
![image](https://user-images.githubusercontent.com/27344419/175894721-ea18b588-50ce-4f69-90da-ad23ea3d0676.png)

![image](https://user-images.githubusercontent.com/27344419/175894754-a2013638-f161-48df-9a7a-65ff96eea66f.png)

![image](https://user-images.githubusercontent.com/27344419/175894780-fc0b45ee-daba-45be-be24-0c92c5a2c550.png)

**Comment by ricmars** [comment]
fixed in github
