### ISSUE TITLE
Change of date on Review transaction screen on click of view

### ISSUE THREAD

**Issue by SudhaAnbalagan27** [pegasystems/uplus-wss#182]
Please check the bug in agile studio for system credentials and config file .
Bug Id : BUG-737129

In wss using dx api, launch Replace a card case and progress the case to Review transaction screen by selecting replacement reason as Lost.

The date field on the screen will be populated with yesterday's date,

Issue: on click of view button the date is getting reduced by 1 day on every click of view button
![image](https://user-images.githubusercontent.com/109672732/179990337-a6500cdb-72ba-47aa-b3fe-648500f76fb7.png)

If no transactions available for the date, then label should be displayed as no transactions available
![image](https://user-images.githubusercontent.com/109672732/179990385-89c38096-a99e-44ec-bbf7-2a7d557ec915.png)

**Comment by ricmars** [comment]
issue has been fixed - note that the paragraph that shows 'no transactions available' has a visibility of false and would not be rendered
