### ISSUE TITLE
Unable to set custom text to upload button

### ISSUE THREAD

**Issue by adithyatalanki** [pegasystems/uplus-wss#183]
In manage customer circumstance case type we have screen to upload documents where we use 'Attach content' control to upload required docs
![image](https://user-images.githubusercontent.com/41073779/183893428-47047c66-4bfc-4325-8144-d46f5aa89f43.png)

But during run time we see the button text as following
![image](https://user-images.githubusercontent.com/41073779/183893472-269b6028-6b87-4918-8582-779ea30ecdf9.png)

Config file and details to reproduce issue are provided on BUG-741859

**Comment by ricmars** [comment]
need to customAttribute Label
![image](https://user-images.githubusercontent.com/29442140/184028231-50eb0719-5d54-43f7-b114-dac404938488.png)
