### ISSUE TITLE
Disable conditions are not applied

### ISSUE THREAD

**Issue by SrideviPatibandla** [pegasystems/uplus-wss#184]
**Describe the bug**
Add disable and read-only conditions to a section - either in the table or field and it is not being applied

**To Reproduce**
For disable condition:
1. In table, add a column and keep disabled condition as always
![image](https://user-images.githubusercontent.com/106650114/185895837-76ccb48f-592d-47a7-ad25-3ce41d866aba.png)
2. Observe that the API response also has the respective flag as expected.
![image](https://user-images.githubusercontent.com/106650114/185896017-404f6acd-1f2d-46c3-b7a5-7ba95f56e9c9.png)
3. Here, the runtime behavior still shows enabled UI. 
![image](https://user-images.githubusercontent.com/106650114/185896374-2474c86b-de0b-4e95-8189-b9a880509628.png)

Similarly, if a field in the section is disabled, even though the JSON response is as expected, it is not reflected in Uplus DX API v1 .

**Comment by ricmars** [comment]
added support for disabled - with dx api v1 - only works if true, false or with when rule
