### ISSUE TITLE
CDH: Hero banner doesn't confirm to page layout

### ISSUE THREAD

**Issue by srob34** [pegasystems/uplus-wss#189]
When using CDH with WSS portal and CDH returns a hero offer to be displayed in place of the default "Set goals, save more" message, the format of the offer stretches to the entire width of the page.  The Polaris icon is also detached and floating to the right of the image which doesn't match the location of Tile offers

**To Reproduce**
Activate CDH with the below parameters

https://omnipw-89prega.pegatsdemo.com
port: 443
V4 of API and Customer context

**Expected behavior**
Offer should appear as the same size and location of the default offer

**Screenshots**
attached

![Screenshot 2023-05-22 at 4 09 34 PM](https://github.com/pegasystems/uplus-wss/assets/7303198/9f015370-bc89-425f-a02d-8bc56e068967)

**Comment by ricmars** [comment]
issue is now fixed on https://pegawss.web.app
<img width="1346" alt="Screenshot 2023-05-24 at 3 52 54 PM" src="https://github.com/pegasystems/uplus-wss/assets/29442140/e3f4d5c7-bb24-48fa-91de-55cf3299fa9c">

please retest and confirm

**Comment by srob34** [comment]
this is working as expected now.  thx!
