### ISSUE TITLE
CDH: Response not captured for Hero banner ad

### ISSUE THREAD

**Issue by srob34** [pegasystems/uplus-wss#190]
**Describe the bug**
When "Enable capturing responses to actions" option is enabled, I see response are captured for the Tile offers below the fold but an Impression isn't captured for the Hero offer.  I recently noticed this behavior with the old WSS but there should be a response captured for all CDH content

**To Reproduce**
Activate CDH at the following
https://omnipw-89prega.pegatsdemo.com
port: 443
V4
Customer context

**Expected behavior**
capture_response is called for an Impression when viewing the Hero offer

**Comment by ricmars** [comment]
issue has been fixed in the latest codebase - capture_reponse should now be sent for the hero content for both the home page and the offer page - not that account page does not support hero content. please retest and confirm the fix so that I can close the issue. Thanks.

**Comment by srob34** [comment]
Richard, seems to be working as expected now.  I see an Impression is captured for the Hero banner.  thx!
