### ISSUE TITLE
CDH: Offer2.html page not displaying dynamic offer 

### ISSUE THREAD

**Issue by srob34** [pegasystems/uplus-wss#191]
**Describe the bug**
When CDH is activated and a user navigates to the offer2.html page, the Container service returns an offer but it isn't displayed on the UI.  Instead this section is blank

**To Reproduce**
Activate CDH on your instance.  Navigate to the Credit cards page in WSS/retail app.  

**Expected behavior**
A Hero offer is displayed int eh center similar to ho the default page looks but populated from CDH

![Screenshot 2023-05-22 at 4 16 16 PM](https://github.com/pegasystems/uplus-wss/assets/7303198/2b88af1e-961a-46bb-ace0-fe0c9120c696)

**Comment by ricmars** [comment]
issue is fixed in latest version
