### ISSUE TITLE
CDH: Reset ExternalID button not copying ID to clipboard

### ISSUE THREAD

**Issue by srob34** [pegasystems/uplus-wss#192]
**Describe the bug**
When demoing the anonymous to known web browsing experience, the user needs to know the ExternalID.  Clicking the ExternalID button can simply display the ID in plain text below the button and automatically copy this value to the clipboard (this is a nice to have but not critical)

**To Reproduce**
open the WSS Settings and then click on CDH.  Click the ExternalID button and try to paste the copied ID to notepad or some other location

**Expected behavior**
Display the ID to be copied or auto copy it to the clipboard

**Comment by ricmars** [comment]
should be fixed in latest codebase - a pop up will display to confirm that the externalID has been copied to the clipboard

**Comment by ricmars** [comment]
please retest - will close issue once confirmed

**Comment by srob34** [comment]
This is working as expected now!  thx
