### ISSUE TITLE
Polaris icon in accounts page is not located near offer image

### ISSUE THREAD

**Issue by 7Tushar** [pegasystems/uplus-wss#195]
**Describe the bug**
Polaris icon in accounts page is not located near offer image.

**To Reproduce**
1. Go to https://multiapp-al89-dev.pegatsdemo.com/docs/retail_bank/
2. Log in as John brown
3. Wait for the offers to load
4. See error: Polaris icon in accounts page is not located new offer image.

**Expected behavior**
Polaris icon in accounts page should be located near offer image.

![image](https://github.com/pegasystems/uplus-wss/assets/50478307/0f164f04-23dd-4624-bc41-f2f42c5c496e)

**Additional context**

**Comment by ricmars** [comment]
issue has been fixed in latest release
