### ISSUE TITLE
Offer details (Basic view) is not loaded when offer is clicked from the chat window

### ISSUE THREAD

**Issue by 7Tushar** [pegasystems/uplus-wss#196]
Offer details (Basic/Detailed  view) is not loaded when offer is clicked from the chat window

**To Reproduce**
1. Go to https://multiapp-al89-dev.pegatsdemo.com/docs/retail_bank/account
2. Login as Carmen Garcia
3. open the chat window and type line of credit
4. Wait for the responses to load and click on Bundled Checking offer
5. Click on "Here are the details for Bundled Checking" link 

**Expected behavior**
Offer details with Basic view should load. This works fine when offer is opened from the web page.

![image](https://github.com/pegasystems/uplus-wss/assets/50478307/6a4daa74-8443-443f-a8ec-b04ed2d756b9)

![image](https://github.com/pegasystems/uplus-wss/assets/50478307/199135ac-2adb-496c-b23b-e7ddab9bda35)

Offer URL : https://multiapp-al89-dev.pegatsdemo.com/Basic?C=SAMPLECON-26&G=UpSell&I=Sales&IXID=-302510526267636812&Chn=IVA&Dir=Inbound&RA=2&Ppn=0.5&O=UpSell&Prt=1.0&T=Checking%20and%20savings&ID=NBA&SID=

**Comment by ricmars** [comment]
enhancement request - build in offer are not accessible by url

**Comment by ricmars** [comment]
enhancement added - use top.postMessage

for example 

`top.postMessage({action: 'showbuiltinoffer', url: '/Basic', img:'./img/offer1.jpg', title:'Offer title', message:'Offer message', benefits: 'Offer benefits', name:'Subscribe', issue:'Acquisition', group:'ProactivePromotion', interactionID: '3223343', channel: 'Web', rank: 2, treatment: 'Tile', contextName:'Customer', container:'NextBestAction'}, location.origin);`
