### ISSUE TITLE
Toggle AI on Accounts page is not readable

### ISSUE THREAD

**Issue by 7Tushar** [pegasystems/uplus-wss#197]
Toggle AI on Accounts page is not readable

![image](https://github.com/pegasystems/uplus-wss/assets/50478307/bbac5160-c5a4-49b1-b30c-29ac48815edb)
![image](https://github.com/pegasystems/uplus-wss/assets/50478307/2ffaa845-ea76-417c-95ec-7932f19e5efb)

**Comment by ricmars** [comment]
issue fixed
