### ISSUE TITLE
What revision of the uplus-wss site am I using?

### ISSUE THREAD

**Issue by marrf** [pegasystems/uplus-wss#2]
**Is your feature request related to a problem? Please describe.**
Can't tell whether the site has been published (changed) since the last time I used it. This is troublesome because I saved a tested/reloaded configuration file and then later that configuration didn't work ... ultimately it didn't work because the site had been updated since time I uploaded the config.

e.g., the config was developed, tested and saved; then some time later uploaded and it didn't work because the site code had changed.

**Describe the solution you'd like**
I would like to have a way to determine that the site has changed since the last time I used it; and what things changed, e.g., an About box or a page footer on the site with tag or label or some equivalent of a revision number ... store the same label in the config-text.json when its generated.

**Describe alternatives you've considered**
I can name the saved config files with a date time stamp and use the date time to review the github change log.

**Comment by ricmars** [comment]
the site is being updated regularly - the highlight of the changes is listed here https://github.com/pegasystems/uplus-wss/wiki 

Configuration is still going thru some changes but we try to support backward compatibility -  it should be possible to use an old config file - Please attach the config file that you have been using -

**Comment by ricmars** [comment]
upgrade logic was added when uploading an older config file - this should not work. see changes added on 5/9  https://github.com/pegasystems/uplus-wss/wiki

**Comment by ricmars** [comment]
closing the issue -
