### ISSUE TITLE
PreviousPage parameter is not set properly

### ISSUE THREAD

**Issue by abhishekchepyala** [pegasystems/uplus-wss#20]
**Describe the bug**
PreviousPage parameter is not set to the offer name

**To Reproduce**
1. Go to uplus_wss retails banking
2. Login with the nanydrummer 
3. Click on learn more for the Overdraft offer. Offer page details will be shown based on the click through url.
3. Now click on the U+Bank logo, the session logged out and the home page is shown instead of the Account Page

**Expected behavior**
Click on the U+Bank logo from the Offer Page is taking to the home page instead of the accounts page. 
Also the PreviousPage parameter is empty

**Screenshots**
[config-text (11).zip](https://github.com/pegasystems/uplus-wss/files/3198052/config-text.11.zip)
![offerdetailspage](https://user-images.githubusercontent.com/50229449/58024421-c167de80-7b2f-11e9-8c60-d271487ac79e.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ricmars** [comment]
regression introduced yesterday when adding support for back browser button - the regression is now fixed and merged.

**Comment by ricmars** [comment]
closing issue

**Comment by abhishekchepyala** [comment]
thanks Richard
