### ISSUE TITLE
Accout details scrren require polishing

### ISSUE THREAD

**Issue by Deepmangal1989** [pegasystems/uplus-wss#200]
![image](https://github.com/pegasystems/uplus-wss/assets/135149142/9cc166dc-8285-432b-8b60-8ef065d01012)
Is this the final account details screen or will it be polished further?

**Comment by ricmars** [comment]
not using the default config - this is how it looks like OOB - yet all the cosmetic changes are done 
<img width="1498" alt="Screenshot 2023-06-05 at 6 37 47 PM" src="https://github.com/pegasystems/uplus-wss/assets/29442140/65a0a717-e0b3-4b6b-af5d-bf426bdc8590">
