### ISSUE TITLE
Polaris icon placement is not proper on offer tile 

### ISSUE THREAD

**Issue by apathimela1** [pegasystems/uplus-wss#202]
**Is your feature request related to a problem? Please describe.**
This is cosmetic issue  

**Describe the solution you'd like**
Placement of Polaris icon can be right top corner of the offer tile ( Post login screen in wss)
![image](https://github.com/pegasystems/uplus-wss/assets/135123554/a518d08e-4f22-45f6-95ec-4d2b8afc4e5f)

**Describe alternatives you've considered**
This is just look and feel issue, nothing functional

**Additional context**
Instance URL : https://multiapp-al89-dev.pegatsdemo.com/uplus-wss-new/retail_bank/account
login with john and look at offer tile on right side

**Comment by ricmars** [comment]
are you sure you are using the latest version of the app? The icons are no longer square - the button is placed on the image
