### ISSUE TITLE
Login page content/images are not loading properly

### ISSUE THREAD

**Issue by Nishant183007** [pegasystems/uplus-wss#204]
**Describe the bug**
In Login page of WSS the content is not shown properly along with images.

**To Reproduce**
1. Go to 'https://multiapp-al89-dev.pegatsdemo.com/uplus-wss/retail_bank'
2. Click on 'Settings'
3. Click on 'Download config file'
4. Go to 'https://pegasystems.github.io/uplus-wss/retail_bank/'
5. Click on 'Settings'
6. Click 'Upload config file' and upload the file you got in step 3 and save
7. Click U+Bank icon at the left top

**Expected behavior**
Issue 1- 'Set goals, save more' should be displayed
Issue 2- Background image should be displayed
Issue 3- Images should be loaded

**Screenshots**
<img width="739" alt="image" src="https://github.com/pegasystems/uplus-wss/assets/61244167/5e53fe7f-3d2b-4ae8-b29d-ea842fa9246d">

Note: We have the offers coming from CDH application in our instance

**Comment by 7Tushar** [comment]
@ricmars can we get a fix for this issue?

**Comment by ricmars** [comment]
provide a hero offer and it will render it correctly

**Comment by Nishant183007** [comment]
> provide a hero offer and it will render it correctly

 Even if we give Tile,Tile, Tile, it is looking for hero offer.
![1058_320_1](https://github.com/pegasystems/uplus-wss/assets/61244167/19ef98dc-da4a-4e0e-b596-7cb144e0dd1f)

**Comment by ricmars** [comment]
confirmed fixed
