### ISSUE TITLE
Actions with microsite are not rendering properly in new WSS

### ISSUE THREAD

**Issue by Nishant183007** [pegasystems/uplus-wss#205]
**Describe the bug**
Actions with microsite are not rendering properly in new design, the images should be displayed without any scroll bars.

**To Reproduce**

Go to 'https://multiapp-al89-dev.pegatsdemo.com/uplus-wss/retail_bank'
Click on 'Settings'
Click on 'Download config file'
Go to 'https://pegasystems.github.io/uplus-wss/retail_bank/'
Click on 'Settings'
Click 'Upload config file' and upload the file you got in step 3 and save
Click U+Bank icon at the left top
Click Loans link
Click Learn more link under 'Get more from your home'
<img width="960" alt="image" src="https://github.com/pegasystems/uplus-wss/assets/61244167/da363fff-4057-4caa-a6a9-2541de60c1f7">

**Expected behavior**
Image and content should be displayed without any scrollbars

**Screenshots**
<img width="960" alt="image" src="https://github.com/pegasystems/uplus-wss/assets/61244167/2cca9840-3d07-4de3-9798-c0326e6fb096">

**Comment by ricmars** [comment]
micro-sites is a deprecated configuration - you built-in

**Comment by ricmars** [comment]
issue should be fixed - please retest and confirm and I will close the issue.

**Comment by ricmars** [comment]
confirmed fixed-
