### ISSUE TITLE
Account page customizations to be exposed in settings

### ISSUE THREAD

**Issue by PreethiBalakrishna** [pegasystems/uplus-wss#206]
**Is your feature request related to a problem? Please describe.**
In order to customize the account page (accountdetails, accountpicker and recentactivity sections) per user, we currently have control from config file as shown below:
Account details:
![image](https://github.com/pegasystems/uplus-wss/assets/57181621/a280c6cf-c767-4b6b-a803-b041d995ff27)
Account picker:
![image](https://github.com/pegasystems/uplus-wss/assets/57181621/6f5922b1-afe7-4757-8176-033396301c56)
Recent Activity:
![image](https://github.com/pegasystems/uplus-wss/assets/57181621/e4dc9611-8c0a-45be-8345-b5b3ba18073c)

**Describe the solution you'd like**
Could this be exposed in the settings of WSS site in the users tab? This would help anyone easily customize the UI.
Also cleanup any redundant unused configurations in user settings like Bill amount which was used for old WSS UI.
![image](https://github.com/pegasystems/uplus-wss/assets/57181621/f101a75c-fa6b-4ee1-83d9-5bb96c05b0ae)

**Comment by ricmars** [comment]
no plan to expose all these configuration in the settings - this is a one off and would require significant work
