### ISSUE TITLE
Support concierge options in chatbot

### ISSUE THREAD

**Issue by Deepmangal1989** [pegasystems/uplus-wss#207]
1)
For a self service user, "My worklist" has been exposed as web embed.

During a chatbot conversation, a case is created by the system and assigned to self service user. 

But there is no ability to refresh the "My worklist/My To-Dos" automatically as soon as a new assignment is created for the user..

As a work-around, in the below video snippet, we are listening for a specific message("My To-Dos") in the chatbot and then triggering explicit refresh of the worklist using some javascript.

2)
Observe in the below video snippet that case launched from chatbot is opening in new tab. 
Expectation is that 
Clicking on a link on Chatbot should be able to open a case directly in web portal. An action in chatbot should be able to trigger refreshing the web portal.

Refer FDBK-102828 on agile studio for more details.

**Comment by ricmars** [comment]
changes are not uplus related - closing request -
