### ISSUE TITLE
Stage names are hidden because of color code

### ISSUE THREAD

**Issue by manoj279** [pegasystems/uplus-wss#209]
Launch an UI kit case with multiple stages. Observe the stage name is hidden because of the foreground and background color being the same.
Refer below screenshot for the same
![image](https://github.com/pegasystems/uplus-wss/assets/22269847/51f25801-d490-4a98-8293-b0b21895a27b)

**Comment by ricmars** [comment]
unrelated to Uplis - this is web mashup 
when you are using Theme-Clarity - the heading is expected to be on a dark background and set to white

add a selector in py-b2c-overrides.css with 
 
.header-content > .header-title {
    color: #414949 !important;
}
