### ISSUE TITLE
In AI overlay text not rendering properly

### ISSUE THREAD

**Issue by apathimela1** [pegasystems/uplus-wss#210]
Upon clicking on Polaris icon ,text not rendering properly

**Reproduce steps:**
1. Navigate to https://multiapp-al89-dev.pegatsdemo.com/uplus-wss/retailbank
2. go to settings page
3. Download the config file.
4. upload the config file in wss settings page
5. navigate to wss and login
6. click on Polaris icon on NBA offer 

**Expected behavior**

![image](https://github.com/pegasystems/uplus-wss/assets/135123554/bf578bd4-59c1-4d0b-92a9-e4c2c9edd2f0)

**Screenshots**

![image](https://github.com/pegasystems/uplus-wss/assets/135123554/938b0cab-6b18-4e76-b9d9-18a01b9d644e)

 - Browser : Chrome 115 version

**Comment by ricmars** [comment]
issue fixed - make AI overlay font-size small - added vertical scroll
