### ISSUE TITLE
Hero Action Learn more text is not visible on button

### ISSUE THREAD

**Issue by apathimela1** [pegasystems/uplus-wss#211]
Hero banner Learn more text is not visible on button

1. Go to 'https://multiapp-al89-dev.pegatsdemo.com/uplus-wss/retail_bank'
2. Click on 'Credit cards' in the header
3. It will show heroaction "Learn the basics of transferring a balance to U+"

**Expected behavior**
Button should display "Learn More " text on button/CTA

**Screenshots**
![image](https://github.com/pegasystems/uplus-wss/assets/135123554/92e81414-b1e8-4b4c-a986-eb216d0b8935)

**Additional context**

Steps to download config file:
1. navigate to https://multiapp-al89-dev.pegatsdemo.com/uplus-wss/retail_bank/
2. click on settings in bottom
3. download the config file

Note : if not seeing heroaction upon clicking on credit cards , go to settings at bottom --->click on Customer decision hub -->make sure your offer contains Hero,tile,tile,tile in placements as shown below
![image](https://github.com/pegasystems/uplus-wss/assets/135123554/60ec5f78-7e60-4771-b950-c6e92b7b38ab)

**Comment by ricmars** [comment]
issue is fixed in the latest release
