### ISSUE TITLE
Hero Action image getting disappearing instantly 

### ISSUE THREAD

**Issue by apathimela1** [pegasystems/uplus-wss#212]
Hero Action image getting disappearing instantly and save more text is missing along with image.

**To Reproduce**
1. Go to 'https://multiapp-al89-dev.pegatsdemo.com/uplus-wss/retail_bank/index.html'
2. Hero action image just disappearing in fraction of seconds.

**Expected behavior**
Able to see stable Hero action image 
**Screenshots**
Hero action:
![image](https://github.com/pegasystems/uplus-wss/assets/135123554/719c652e-e7ac-4803-881e-3f14fe8307a4)

currently we see it as
<img width="963" alt="image" src="https://github.com/pegasystems/uplus-wss/assets/135123554/90a90a23-d4c6-4430-b856-e9a9fb94c48b">

Steps to download config file
1. navigate to https://multiapp-al89-dev.pegatsdemo.com/uplus-wss/retail_bank/index.html
2. click on settings at bottom
3. download config file.

**Comment by ricmars** [comment]
fixed in 2.0.3 https://github.com/pegasystems/uplus-wss/releases/tag/2.0.3
