### ISSUE TITLE
Case Header missing for Uikit cases launched via quicklinks

### ISSUE THREAD

**Issue by Deepmangal1989** [pegasystems/uplus-wss#224]
1) Create a mashup channel (uikit) in any of the pega instance.
2) Configure that as quicklink in the WSS.
3) Launch the case and observe that the Case header does not show up. 

![image](https://github.com/user-attachments/assets/4b34ab7c-5128-44d6-86d6-592ee6063cc6)

![image](https://github.com/user-attachments/assets/348d5f3b-d2ec-4652-b28f-99c635e299fb)

**Comment by ricmars** [comment]
the new version of uplus-wss v2 is focused on Constellation and web-embed - the new version does not work well with the old Clarity Theme and Pega Web Mashup where the h1 of the case header was white and set on the background of the header

The version 1.x of the application is available on https://pegawss.web.app/ - you can also download the latest version here https://github.com/pegasystems/uplus-wss/tree/release/1.x

The header is likely there but it has a white color - use browser dev tools
