### ISSUE TITLE
Unknown customer issue on mobile

### ISSUE THREAD

**Issue by SravaniKN** [pegasystems/uplus-wss#26]
**Describe the bug**
On Mobile, when we click on Chat with agent we are getting call to CSR as unknown customer.

**To Reproduce**
1. Go to wss in mobile, uplaod the attached config file.
2. Login with Nancy Drummer
3. Once Overdraft offer is shown on Home screen Click on Need help
4. click on Chat with Agent
5. Click on I have a general question
6. Type some random text.

Issue: Obeerve that, when chat is escalated, it is coming as Unknown customer.

**Expected behavior**
Expected to have customer name in call

 
**Smartphone (please complete the following information):**
 - Device: [e.g. Redmi Note4]
 - OS: [e.g. Android]
![Screenshot_2019-05-22-17-17-20-627_com android chrome](https://user-images.githubusercontent.com/50488225/58176557-281c0200-7cc0-11e9-9cc9-bef3c24a7c3d.png)
![9a6bb17e-9224-45ff-8b76-7c890f3216b9](https://user-images.githubusercontent.com/50488225/58176561-29e5c580-7cc0-11e9-93bd-84b666080a6c.png)

**Comment by ricmars** [comment]
issue is now fixed on mobile

**Comment by SravaniKN** [comment]
Its working fine now. Thanks Richard.

**Comment by SravaniKN** [comment]
Hi Richard,
Unknown customer issue is now coming in desktop. could you please look into this on high priority? 
![web_Unknowncustomer](https://user-images.githubusercontent.com/50488225/58539678-7af03f00-8215-11e9-8a5b-23ea37fe611b.PNG)

**Comment by ricmars** [comment]
you need to open chat after being logged in
