### ISSUE TITLE
Chat is not responsive on mobile

### ISSUE THREAD

**Issue by SravaniKN** [pegasystems/uplus-wss#27]
**Describe the bug**

Chat is not responsive on mobile. getting horizontal scroll bar

**To Reproduce**
1. Go to wss on mobile. Import the file attached.
2. Login with Nancy drummer
3. Click on Need help
4. Click on Chat with agent
5. Click on I have a general question
6. Type some random text

Issue: Observe that chat is not responsive and getting horizontal scroll bar to scroll right and left to view the full content.

**Expected behavior**

Expected that chat should be responsive on mobile.

**Smartphone (please complete the following information):**
 - Device: [e.g. RedmiNote4]
 - OS: [e.g. Android}
 
![Screenshot_2019-05-22-17-17-20-627_com android chrome](https://user-images.githubusercontent.com/50488225/58176865-de7fe700-7cc0-11e9-9b71-2345e6b5eacd.png)
[config-text_82s.zip](https://github.com/pegasystems/uplus-wss/files/3207483/config-text_82s.zip)

**Comment by ricmars** [comment]
closing the issue - it is a chat issue and not a uplus wss issue
