### ISSUE TITLE
Chat does not reset on log out and log in 

### ISSUE THREAD

**Issue by 7Tushar** [pegasystems/uplus-wss#3]
**Describe the bug**
Chat conversation is persisting even when we log out and log in with a different user. Ideally , when we log out, the chat should also reset with the configured welcome message.

Currently, if we log in with User A and do some chat conversation, log out and log in with User B, the chat done by User A still shows up.

**To Reproduce**
1. Go to https://pegasystems.github.io/uplus-wss/retail_bank/
2. Log in with User A and click on Need help
3. Do some chat conversation
4. Click log out and log in with User B and click on Need help

**Expected behavior**
The chat should reset and configured welcome message should be displayed. The existing chat conversation should not be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/50478307/57509401-c81d7700-7321-11e9-9c92-6977caceb215.png)

![image](https://user-images.githubusercontent.com/50478307/57509420-d2d80c00-7321-11e9-88e7-127da1afebf7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by ricmars** [comment]
I will add a new option in the chat bot settings to reset chat on logout

**Comment by 7Tushar** [comment]
Hi Richard, we validated this after your fix but the chat is still not resetting on log out.

**Comment by ricmars** [comment]
the reset of the chat is still not implemented - I am having issue clearing the Chat bot JSESSIONID cookie due to security issues. What is implemented is that on logout, the chat session iframe is recreated and the AccountID and ContactID are no longer passed to the Chat session.

**Comment by ricmars** [comment]
closing bug - the reset of the chat is an enhancement - created new feature request
