### ISSUE TITLE
Dynamic hero content on home page

### ISSUE THREAD

**Issue by srob34** [pegasystems/uplus-wss#30]
To demonstrated Pega Marketing on WSS, I'd like to request the static text at the top of home page be updated to optionally be dynamic, populated from Pega Marketing.

In the Pega Marketing Settings, this area should be populated when there is a placement type of Hero specified for the page.

![Screen Shot 2019-05-22 at 12 16 35 PM](https://user-images.githubusercontent.com/7303198/58191279-35b79480-7c8c-11e9-9fe1-f853fead1e96.png)

**Comment by ricmars** [comment]
feature has been implemented and merged.
