### ISSUE TITLE
Chat bot is not responsive on mobile

### ISSUE THREAD

**Issue by SravaniKN** [pegasystems/uplus-wss#4]
Chat is not rendering properly on mobile device.

1.  Open WSS on mobile. (Go to 'https://pegasystems.github.io/uplus-wss/retail_bank/index.html')
2. Click on 'Need Help'

3. See that, UI is not rendering properly. 

**Expected behavior**
Expected to have responsive UI on mobile and other tablet devices.
![Screenshot_2019-05-10-12-24-26-427_com android chrome](https://user-images.githubusercontent.com/50488225/57530366-b43f3880-7354-11e9-8c23-d23bec52f714.png)
![Screenshot_2019-05-10-13-03-05-689_com android chrome](https://user-images.githubusercontent.com/50488225/57530367-b43f3880-7354-11e9-9eaf-d2b1fbc14fe2.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Redmi Note4/ Samsung Gallaxy ]
 - OS: [e.g. Android]

**Comment by ricmars** [comment]
width of the chatbot iframe reduced from 450px to 300px on a mobile device. Height is unchanged. Closing the issue
