### ISSUE TITLE
Account section marketing offer height issue

### ISSUE THREAD

**Issue by Yarramneni-vasavi** [pegasystems/uplus-wss#40]
When we try to launch the Marketing offer from the account section, The height of the offer screen is very small. (Screenshot #1)

1. Upload the attached config file attached. 
[health_payer-config.zip](https://github.com/pegasystems/uplus-wss/files/3216005/health_payer-config.zip)
1. Go to WSS login page. Login as 'BethAMiller74@pegatsdemo.com'
2. Click on Offer in the account section.
3. Observe the height of the screen and the scroll bar on the right.

Screenshot 1:
![2019-05-24 14_23_00-](https://user-images.githubusercontent.com/10959887/58315621-7ef41980-7e2f-11e9-9636-cd68b50403a2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by avinay** [comment]
We see the same issue with retail banking as well, as iframe height has changed from 570px to 100%,
Can we also try setting section element above iframe to 100% as well.
![scroll-issue-screenshot](https://user-images.githubusercontent.com/572447/58328077-d190fe00-7e4e-11e9-9624-6f8742259c21.png)

**Comment by ricmars** [comment]
issue has been fixed and merged - class height-100-pct has been added
