### ISSUE TITLE
Assignment in account section not Visible on the First launch

### ISSUE THREAD

**Issue by Yarramneni-vasavi** [pegasystems/uplus-wss#42]
When we login into the WSS portal,  the assignment section is not visible. but on browser refresh it is visible.

1. upload the config json file 
[health_payer-config.zip](https://github.com/pegasystems/uplus-wss/files/3217327/health_payer-config.zip)
1. Go to WSS home page and login as 'BethAMiller74@pegatsdemo.com'.
2. Observe the assignment section is not visible.
3. Try refreshing the browser, then the assignment section is coming.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ricmars** [comment]
Please retest - I made some changes in how the Mashup is loaded so that only one MashupScript is now loaded between the different instances - that should address the issue.

tried with the attached config file against lab5026: refresh / login -> account todo list in the mashup loads correctly

**Comment by Yarramneni-vasavi** [comment]
Thanks Richard, Issue is fixed.
