### ISSUE TITLE
Scroll bar issue in offer.html

### ISSUE THREAD

**Issue by manoj279** [pegasystems/uplus-wss#43]
Description:
When we try to launch the service case by clicking on "Get a quote" we observe a horizontal scroll inside the iframe.

Expectation:
The iframe should be responsive by accommodating the content.

    Upload the attached config file attached.
[config-text (3).zip](https://github.com/pegasystems/uplus-wss/files/3222200/config-text.3.zip)

    Go to WSS login page. Click on "Learn more" under "Travel smart".
    Click on "Get a quote"
    Observe the width of the screen and the scroll bar on the bottom.

PFA
![offer](https://user-images.githubusercontent.com/22269847/58400923-164cad00-807a-11e9-852c-4f572acee072.png)
![offer1 html](https://user-images.githubusercontent.com/22269847/58400928-16e54380-807a-11e9-91c0-b3e30df55da7.png)

**Comment by ricmars** [comment]
the width was limited to 730px for the mashup for the offer page - increased the width to 1100px. Note that this service case is not responsive and requires a 910px minimum width - it is important that any service case is responsive and does not cause vertical scrollbar - the table must be set to responsive and you should set every field in the table to wrap
