### ISSUE TITLE
Scroll bar issue in service case 

### ISSUE THREAD

**Issue by Yarramneni-vasavi** [pegasystems/uplus-wss#46]
When the service case is loading it is coming with vertical scroll bar. the service case is using a screen flow. (Screenshot 1)

1. upload the attached config file. 

[HealthPayer-Config.zip](https://github.com/pegasystems/uplus-wss/files/3223243/HealthPayer-Config.zip)

2. Go to WSS and login as 'BethAMiller74@pegatsdemo.com'
3. In the account section, Click on 'WelcomeMember' service case from quick links.
4. Observe the vertical scroll bar issue.

**Expected behavior**
Scroll bar should not occur. iframe should be responsive

Screenshot 1:
![2019-05-27 15_29_10-](https://user-images.githubusercontent.com/10959887/58412584-62a4e680-8094-11e9-95b8-37ebde4e5f6e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74.0

**Comment by ricmars** [comment]
issue should be fixed in the Clarity theme - we should not set display:inline-block on workarea-view-content

**Comment by Yarramneni-vasavi** [comment]
Issue is fixed after consuming latest platform build - 7481
