### ISSUE TITLE
Issue with offers image in commercial banking while switching

### ISSUE THREAD

**Issue by SureshBabuSabbu** [pegasystems/uplus-wss#48]
In Commercial Demo, we were getting the same image for both Business Service and FX Volatility but the content is changing properly.

While Login we need to show the Business Services Offer by default. Whereas When we launch the Payment Inquiry Case and on completing the case we need to show the FX Volatility offer.
This was working couple of days ago. But with the recent changes in GitHub we were not getting the Image properly where as the content is changing underneath the image.

**Screenshots**
[config-text-Commercial.txt](https://github.com/pegasystems/uplus-wss/files/3227674/config-text-Commercial.txt)

![Business Service](https://user-images.githubusercontent.com/51121722/58479414-e256b200-8175-11e9-9bac-51db2d036942.jpg)
![FX](https://user-images.githubusercontent.com/51121722/58479415-e256b200-8175-11e9-8a5c-2402866fd2f3.jpg)

**Comment by ricmars** [comment]
not a bug - This is a config issue in your offer – the imageURL comes back as empty and as such it uses the default image called img/option-1.jpg
 
https://fspw19commercialserviceexcellence.pegatsdemo.com/prweb/PRRestService/PegaMKTContainer/V2/Container?ContainerName=TopOffers&CustomerID=PEGASAFS-WORK-CONTACT%20CON-1006
