### ISSUE TITLE
Offer image is not displaying though it is uploaded into Git folder

### ISSUE THREAD

**Issue by Yarramneni-vasavi** [pegasystems/uplus-wss#50]
For Offer microsite we have 'ERAlternatives.jpg' image to display. The same image file is present in Git location (public/health_payer/img/ERAlternatives.jpg) but still we are unable to see the offer image.  (refer to the screenshot below)

Upload the attached config json file.

[HealthPayer-Config_69.zip](https://github.com/pegasystems/uplus-wss/files/3231811/HealthPayer-Config_69.zip)

1. Launch WSS health_payer Git URL (https://pegasystems.github.io/uplus-wss/health_payer)
2. Login as 'BethAMiller74@pegatsdemo.com'.
3. Observe the offer image is not displaying. 
4. Observe in git the image with same name is already present.

**Expected behavior**
Once the image is uploaded in git location, it should be visible.

Screenshot 1:
![2019-05-29 15_16_08-Gladiators - Vasavi Yarramneni@in pega com - Outlook](https://user-images.githubusercontent.com/10959887/58547510-1937d100-8225-11e9-95a8-86b68e42c7fa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 74.0

**Comment by ricmars** [comment]
issue is fixed - you need to check the docs folder to see if the image is present - the public is used for the source - https://github.com/pegasystems/uplus-wss/tree/master/docs/health_payer/img 

the image filename is img/ERAlternatives.jpg

note that as a best practices, it is better to have the images sources from the Pega Marketing system
