### ISSUE TITLE
Scroll bar Issue on Mobile

### ISSUE THREAD

**Issue by ricmars** [pegasystems/uplus-wss#53]
Steps to reproduce:

 

Launch https://pegasystems.github.io/uplus-wss/insurance/ on android mobile

Scroll to the bottom of the page and click on Settings

Click on upload icon on top right corner and import the config file attached.

Goto screen -4 Accident photos

When we add more number of photos the "Add photos" link disappears.

Instead it should allow the user to scoll down the page.

 

Harness Used: TreenavigationforScreenFlow

**Comment by VidyaMenon** [comment]
This is a critical issue for FS retail. Please access this hyperlink http://tinyurl.com/y6x8ykyl . We are using this to launch a service case in quick links through the local copy of GitHub wss. And we are unable to scroll the screen, hence cant proceed with the demo scene. After accessing hyperlink, click on open banking to start the service case. Surprisingly when we launch a case from clicking learn more on offer, this scroll bar issue is not present. Click on Overdraft- learn more from same hyperlink to see this behavior. We are not launching microsite, but a regular csfs case from offer learn more also.

**Comment by ricmars** [comment]
issue should be fixed
