### ISSUE TITLE
Scroll bar issue in Offer Mashup

### ISSUE THREAD

**Issue by SravaniKN** [pegasystems/uplus-wss#55]
**Describe the bug**
We are getting scroll bar in Offer mashup screen (Desktop and Laptop) and it is not responsive.

[Mary_config-text-82s.zip](https://github.com/pegasystems/uplus-wss/files/3240225/Mary_config-text-82s.zip)
1. Go to new wss and upload the attached file.
2. Login as "Mary"
3. click on Learn more in the Overdraft section

Issue :Observe that scroll bar is coming and screen is not responsive. Same observed in desktop and laptop

**Expected behavior**
No Scroll bars should come and screen should be responsive in Desktop/Laptop as well.

Desktop / Laptop
![scrollbar](https://user-images.githubusercontent.com/50488225/58688888-4d390080-83a3-11e9-93c7-0058762649b7.PNG)

**Comment by ricmars** [comment]
issue is fixed
