### ISSUE TITLE
How to receive parameters set for a certain user in a to-do gadget?

### ISSUE THREAD

**Issue by jortizclaver** [pegasystems/uplus-wss#59]
Hi,

We are building a to-do gadget where the we would need to receive the customer identifier associated to the WSS login. Where will those parameters be received?

Regards,
Jorge

**Comment by ricmars** [comment]
look at the user settings in the uplus app - the accountID and customerID will be passed to the todo list mashup. Also any parameters added to the extra params will also be sent - look at the url of the todo list mashup iframe to see what are the parameters sent.
