### ISSUE TITLE
Account details in the section “AutoPayAccountDetails” need to be shown in a separate column tile for the manage autopay case in WSS.

### ISSUE THREAD

**Issue by siris2** [pegasystems/uplus-wss#6]
**Describe the bug**
Account details in the section “AutoPayAccountDetails” need to be shown in a separate column tile for the manage autopay case in WSS.

**To Reproduce**
Upload the attached github json config file ConfigFile1
Login as Dan Cooper
In quick links click on Manage Autopay to launch the case

**Expected behavior**
Account details in the section “AutoPayAccountDetails” need to be shown in a separate column tile for the manage autopay case.

**Screenshots**
Detailed screenshots are available in the attachments

NOTE: Change the extension of config file to json

[Account details in separate tile issue.docx](https://github.com/pegasystems/uplus-wss/files/3177220/Account.details.in.separate.tile.issue.docx)
[ConfigFile1.txt](https://github.com/pegasystems/uplus-wss/files/3177221/ConfigFile1.txt)

**Comment by ricmars** [comment]
not a bug with the WSS Uplus app - your Mashup needs to implement the secondary card - You will need to override the OTB TreeNavigationMain to add the card on the right - I provided an example - see other industry like Comms or Health care who implemented similar functionality
