### ISSUE TITLE
Ability to expand automatically the chat window on load

### ISSUE THREAD

**Issue by ricmars** [pegasystems/uplus-wss#62]
When a certain customer “logs” in, he would like to proactively launch the chatbot

By default the chat window is collapsed when loading the portal. Need to expose a setting that would expand the chat window automatically on load of the portal.

Launching the bot requires nothing more than calling the InvokeAdvisor function in the helper JS File

A new setting need to be exposed to turn on this functionality

**Comment by AlexKing2289** [comment]
> When a certain customer “logs” in, he would like to proactively launch the chatbot
> 
> By default the chat window is collapsed when loading the portal. Need to expose a setting that would expand the chat window automatically on load of the portal.
> 
> Launching the bot requires nothing more than calling the InvokeAdvisor function in the helper JS File
> 
> A new setting need to be exposed to turn on this functionality

**Comment by gurus4283** [comment]
We already have this feature from Customer Service. It is called Proactive Notification introduced in Customer Service 8.4.

**Comment by ricmars** [comment]
closing enhancement since already available in 8.4
