### ISSUE TITLE
Government : BillPay mashup not working

### ISSUE THREAD

**Issue by raghuveerbathini** [pegasystems/uplus-wss#64]
**Describe the bug**
In the Government WSS website, mashup configured on the BillPay is not working.

**To Reproduce**
1. Go to https://pegasystems.github.io/uplus-wss/gov 
2. Click on Settings
3. Configure mashup for the BillPay. (such as display Harness)
4. Click on Submit.
5. Login to the WSS Portal. 

**Expected behavior**
The mashup configured for the BillPay should be shown.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version : 67

**Comment by ricmars** [comment]
works fine for me - without a config file attached to the bug it is hard to debug but I tried with my own Mashup configuration and it worked fine
![Screen Shot 2019-06-19 at 5 32 26 PM](https://user-images.githubusercontent.com/29442140/59803036-59d0ba80-92b8-11e9-8af0-0205ccfda831.png)
