### ISSUE TITLE
Unable to render section pyB2CCaseMainConfirm in WSS

### ISSUE THREAD

**Issue by manoj279** [pegasystems/uplus-wss#65]
Unable to render section pyB2CCaseMainConfirm in Themeclarity Ruleset.
We tried using private edit mode and noticed the error shown in image.

Issue might be due to the property reference (D_prevTask.pyNextlabel) in dynamic layout3.
(Display header check box is checked)

![image](https://user-images.githubusercontent.com/22269847/59764296-204c7f00-92b9-11e9-8600-f289146b60dc.png)

**Comment by ricmars** [comment]
fixed in Theme-Clarity:01-01

**Comment by ricmars** [comment]
removed the unneeded cell from the header
