### ISSUE TITLE
Section pyToDoList at Assign-

### ISSUE THREAD

**Issue by jortizclaver** [pegasystems/uplus-wss#66]
**Is your feature request related to a problem? Please describe.**
The section pyToDoList sits at Assign-Worklist but it does not have anything specific to Worklist. Consumer applications using Workbasket instead cannot reuse it.

**Describe the solution you'd like**
If the section was moved from Assign-Worklist to Assign-, applications would be able to use for both Worklist and Workbaskets.

**Describe alternatives you've considered**
Applications creating a copy at Assign- level (not good for maintenance).

**Additional context**

**Comment by ricmars** [comment]
no plan to fix in Clarity Theme - you can create a new section if needed
