### ISSUE TITLE
LockInfo harness not managed by pyB2CCaseMainInner

### ISSUE THREAD

**Issue by jortizclaver** [pegasystems/uplus-wss#67]
**Is your feature request related to a problem? Please describe.**
When a work object is locked, the system renders LockInfo harness, which does not seem to be managed by pyB2CCaseMainInner

**Describe the solution you'd like**
pyB2CCaseMainInner could be modified to manage this harness as well. Display a brief user-friendly comment and give option to come back.

**Describe alternatives you've considered**
Each applications to build its harness

**Additional context**

**Comment by ricmars** [comment]
in 8.3, the lockInfo harness is updated in the Clarity theme to be more user friendly
![image](https://user-images.githubusercontent.com/29442140/61392015-f3759280-a88b-11e9-9d2c-38b40dca02e9.png)
