### ISSUE TITLE
PostMessage event to launch a mash up case

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#68]
We have a use case in fs retail where we launch a microsite flow on click of an offer. In a screen in this flow, we need a button, on click of which we have to launch an entirely new mashup case from another application. Is it possible to provide an ability to post a message with the url so that the mash up case can be launched, as it would be launched on click of the quick link url.

**Comment by ricmars** [comment]
no plan to address this enhancement - closing the issue
