### ISSUE TITLE
Ability to hide a quick link url

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#69]
We have a use case in fs retail where we have to send a url in a text message, on click of which a mashup case needs to be launched. We are using the quick link url in the text message. But for this to work, we need to have this configuration in the json config file. This means that it will show up as a link in the right side of the wss when someone logs in. We do not want these links to be shown in wss. we only want this invoked from the text  message. Can a setting be provided in the config file which can help to hide a certain case from appearing in the quick links area of wss, but still allows to invoke the case from text message etc.

**Comment by ricmars** [comment]
Added ability to hide a quicklink from the account page - go to the 'Quick Links' page under Settings and check the checkbox 'Hide from account page' to hide it from the account. The quicklink can still be accessed through the shortcut url using index.html?pega_userid=foo&quicklinkclass=Work-Test
