### ISSUE TITLE
To launch Manage Autopay in the WSS with parameters accountid and contactid in the users tab instead of the comma separated params in quick links tab

### ISSUE THREAD

**Issue by siris2** [pegasystems/uplus-wss#7]
**Describe the bug**
To launch Manage Autopay in the WSS with parameters accountid and contactid in the users tab instead of the comma separated params in quick links tab

**To Reproduce**
Upload the attached github json config file ConfigFile2
Login as Dan Cooper
In quick links click on Manage Autopay to launch the case
The case will not launch and an error will be thrown

**Expected behavior**
Manage autopay case needs to be launched properly as it happens if the accountid and contactid are passed via extra params in quick links

**Screenshots**
Detailed screenshots are availabke in the document attached

NOTE: change the extension of config file to json

[Accountid and contactid issue in users tab.docx](https://github.com/pegasystems/uplus-wss/files/3177238/Accountid.and.contactid.issue.in.users.tab.docx)
[ConfigFile2.txt](https://github.com/pegasystems/uplus-wss/files/3177239/ConfigFile2.txt)

**Comment by ricmars** [comment]
the names of the parameters to look for in the Pega application are 'AccountNumber' and 'ContactId'
