### ISSUE TITLE
Ability to open a mash up case directly from deep link in mobile

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#70]
From the desktop when we create a deep link and click it, it directly opens the case. But in mobile, we need to click the middle icon again to launch the case. We have use cases where we send 3 different case links in FS retail at different stages in the flow..But for all of them , it shows the same name in the icon when the url is clicked. Is it possible to directly launch the case on click of url, instead of bringing them to home screen. ie to mimic the same behavior as desktop?

**Comment by ricmars** [comment]
Fixed issue with quicklink on mobile - Now when using the quicklink, the mashup will be shown immediately instead of the home screen
