### ISSUE TITLE
Dropdown having extra padding

### ISSUE THREAD

**Issue by manoj279** [pegasystems/uplus-wss#71]
We used a dropdown property in table layout and when we click on it it gets position is lowered.

![image](https://user-images.githubusercontent.com/22269847/60339163-a22d5e00-99c5-11e9-906a-ea63515b9086.png)

CSS for the respective cell:

![image](https://user-images.githubusercontent.com/22269847/60339200-c0935980-99c5-11e9-9c26-18b5c56399d9.png)

**Comment by ricmars** [comment]
this is not a uplus wss issue
