### ISSUE TITLE
To Do does not pick the context of the user logged in

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#73]
We have a use case in FS retail where we have multiple customers/users and we have to show their to do list. The to do list harness uses a report definition that uses pxRequestor.pyUserIdentfier to fetch the work list items for that operator. When we login with a certain user to WSS, it uses the pegauserid associated with that user to fetch the worklist items. But now if I logout and login with another user, it shows me the worklist items of the previous user itself, as the pxRequestor is not changing. Upon logout, the session should be terminated and when logging in a new pxRequestor should be created. Without this, we are having issues where each user is logging in to different applications. For example user 1 logs into SAFS and user 2 logs in to CSFS. now when I configure to do, I can only give one application context. I give SAFS. but now when the user2 tries to login, the corresponding pegauserid does not have access to SAFS application and I get an authentication error on screen. Either I should have an option to hide the to do list for certain users in the config tab, so I show it only for users who point to SAFS application, or the pxRequestor should be picked from the logged in user.

**Comment by VidyaMenon** [comment]
I realized I could add SAFS as a secondary access group to the first user and avoid the authentication error. So now the issue is only that if I logout and login as another user, they see the worklist of first user and not the current logged in user.

**Comment by ricmars** [comment]
issue fixed - on logout of the WSS, will issue a request against the TODO mashup url to force a logout and close the requestor - retested with 2 different users and confirmed that the list of items in the todo list is now correct
