### ISSUE TITLE
goToDashboard function on mobile does not bring us back to main screen

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#75]
when we run a service case from mobile, at the confirmation screen, we have a button on click of which we are calling the function goToDashboard. This behaves different in mobile compared to desktop. Can we have the same behavior in mobile as well? Currently it goes to a screen which shows a list of quick link urls.

**Comment by ricmars** [comment]
there is no goToDashboard function - I assume that you are referring to the API pegaMashupNavigateBack - right ?

**Comment by ricmars** [comment]
changed how pegaMashupNavigateBack works on mobile - will now go to the home page
