### ISSUE TITLE
Ability to dynamically pass parameters for deep link urls

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#76]
We have a use case in FS retail where we want to click a link in an email or text message and open a service case in wss. we are using the deep link url for this with pegauserid and class name as parameters. It is picking the remaining parameter values associated with the pegauser id from the config file. But these are all static values. We have a use case where we need to pass an interaction id associated with an offer to this service case. This interaction id is dynamically created from a previous case, hence we cannot set the value in the config file. Is there an option to pass this value dynamically as a parameter when we create the url. When we create the url, we can get the value from a data page and set it. Will it be possible to set this dynamic value to the new case created when clicking this hyperlink?

**Comment by ricmars** [comment]
Provided the ability to pass extra parameters through a quicklink. The extra params are passed as is to the Mashup iframe. For example, if you use index.html?pega_userid=foo&quicklinkclass=Work-Test&param1=value1&param2=value2 then the Mashup for the quicklink will receive the parameters param1 and param2.
