### ISSUE TITLE
Go back to home page

### ISSUE THREAD

**Issue by malyr1** [pegasystems/uplus-wss#77]
For Comms vertical, we had a use case:  We are launching one service  from home page of WSS and after completion, we come back to home screen. Script is not available.

After login to WSS, we have a script to come back to account screen, but before login scripts is not available. Need a script.

Discussed with Richard and creating feature request on this.

**Comment by ricmars** [comment]
this is working as expected - in the Mashup opened from the home page (Home hero action) - if you have a button that has a runscript with "pegaMashupNavigateBack", it will navigate back to the home page.

You need to make sure that your Mashup is using pyB2CCaseMainInner from Theme-Clarity. This section has the non auto section pyB2CActionAreaInc that implements the API pegaMashupNavigateBack

**Comment by ricmars** [comment]
closing bug as not reproducible
