### ISSUE TITLE
Unauthenticated access to start a service case in WSS from deep link url

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#78]
In FS Retail, we have a prospect use case where clicking on a paid media ad, we want the prospect to be redirected to a microsite case. Since it is a prospect, they will not log in. When we use a deep link url without a pegauser id, it just brings us to the home page. Is there a possibility to start the case and show the first screen without the user login, when clicking on a url? If we pass only the class name in the url and no pegauser id? Based on discussion with Richard, we are trying to use guest access using a new auth service.  This enhancement request is to remove the restriction from WSS side and show the mashup without being authenticated when such a URL is received.

**Comment by ricmars** [comment]
added enhancement to open directly the Mashup for Home hero action, bill pay, KM help and Offer action

7/29/2019
	•	Provided the ability to go directly through the Mashup for the following use cases:
	1.	To show the Home hero action - set the url parameter index.html?homeHeroAction=1
	2.	To show the Offer action - set the url parameter offer.html?offerAction=1
	3.	To show the Bill pay action (needs username) - set the url parameter index.html?pega_userid=xx&viewBill=1
	4.	To show the KM Help (needs username) - set the url parameter index.html?pega_userid=xx&viewKMHelp=1

**Comment by ricmars** [comment]
change merged
