### ISSUE TITLE
Issue with AccountID in settings users tab

### ISSUE THREAD

**Issue by abhishekchepyala** [pegasystems/uplus-wss#8]
**Describe the bug**
AccountID in users tab is behaving differently.
For Marketing Offer AccountID is expecting Customer ID 'PEGASAFS-WORK-CONTACT CON-733'

`{CustomerID: "PEGASAFS-WORK-CONTACT CON-913", ContainerName: "TopOffers", Channel: "Web",…}
Channel: "Web"
ContainerName: "TopOffers"
Contexts: [{Key: "CurrentPage", Value: "index.html", Type: "CurrentPage"},…]
CustomerID: "PEGASAFS-WORK-CONTACT CON-913"` 

For mashup in quick links, AccountID is expecting the AccountNumber, but we have set the value to CustomerID for marketing offer. Hence CustomerID is passed as the AccountNumber as shown below

`pyActivity: @baseclass.doUIAction
action: createNewWork
isWebMashup: true
className: PegaFS-SCM-Work-ManageAutoPay
flowName: pyStartCase
pzSkinName: ClaritySkin_Mantis
pyMashupSkeletonName: pyDefaultMashupSkeleton
UserIdentifier: FSSelfServiceUser
Password: aW5zdGFsbDEyMzQ1IQ==
AccountNumber: PEGASAFS-WORK-CONTACT CON-913
ContactId: 1557350040
IsWSSQuickLink: true`

It is conflicting and not able to launch the mashup, I am getting the below error
**.AccountNumber: "PEGASAFS-WORK-CONTACT CON-913" is too long, maximum length allowed is 16**

**To Reproduce**
1. Go to 'https://pegasystems.github.io/uplus-wss/retail_bank/index.html'
2. Upload the attached config file.
2. LogIn with MaryFischer
3. Under quick links click on Setup Autopay
**.AccountNumber: "PEGASAFS-WORK-CONTACT CON-913" is too long, maximum length allowed is 16**

Note: AccountID is specific to customer and i cannot mention it under extra parameters in quick links

**Expected behavior**
It should launch the mashup content 

**Screenshots**
[config-text (1).zip](https://github.com/pegasystems/uplus-wss/files/3177375/config-text.1.zip)
![error](https://user-images.githubusercontent.com/50229449/57694721-160be500-766a-11e9-8b1a-8ac2791d5eca.PNG)

**Comment by ricmars** [comment]
Added a new parameter under user settings: SubscriberID - the SubscriberID will be passed to Pega Marketing to get the offer - this avoid the issue where the accountID was used for both subscriberID and mashup parameter.
