### ISSUE TITLE
Need to remove left,right,bottom borders for date time control (Type:DateRange) in CSI WSS

### ISSUE THREAD

**Issue by SukanyaVysyaraju** [pegasystems/uplus-wss#86]
Launch https://lab5134.lab.pega.com/uplus-wss-master/docs/insurance
Click on Login
And click Travel from Quick links
We are using date ime control (Type:Date Range) in one section
When we use that section in WSS, we are getting borders in all sides

Note: We are not getting borders(except bottom border) for date time control which is of type Date
![image](https://user-images.githubusercontent.com/51997999/63517648-fa3b9900-c50c-11e9-8b29-d6b5d07ec821.png)

![image](https://user-images.githubusercontent.com/51997999/63517654-fe67b680-c50c-11e9-9b78-261196df67c7.png)

**Comment by ricmars** [comment]
this is a Pega issue not a github  - there is border for the control - if you don't see it is because it is being truncated due to some height issue - check your dynamic layout - from the screenshot, you can see that the border style is set.

**Comment by SukanyaVysyaraju** [comment]
@ricmars Created BUG-506348 for pega UI team. As per their comments in bug, we need to override DateRange's CSS class(rdOnlySpn) in clarity skin to remove borders.

Should we override rdOnlySpn class in vertical specific CSS or should we make change in generic clarity skin?
