### ISSUE TITLE
ToDo list gadget does not appear in Edge

### ISSUE THREAD

**Issue by jortizclaver** [pegasystems/uplus-wss#88]
We are testing our WSS to-do gadget in all Pega supported browsers and we could not make it work for Edge. We dont see any attempt to connect to the server what seems to indicate that there could be some kind of issue at the browser side. Is there any known limitation using this this gadget with Edge? 

Configuration file attached: [config-text.json (2).zip](https://github.com/pegasystems/uplus-wss/files/3551656/config-text.json.2.zip)

**Comment by ricmars** [comment]
uplus works fine with edge - there is something with the lab system that edge does not like likely related to CORS. the request to download the script or load the url from the iframe is blocked.
edge is working fine with another system.
closing the bug

**Comment by jortizclaver** [comment]
We tried against other environments and we always get the same problem in Edge. Would you have the configuration file and details of another system where the todo list is working so that we can compare?
