### ISSUE TITLE
Insurance team related information is displaying in Communications mobile self service  

### ISSUE THREAD

**Issue by Rajesh2016185** [pegasystems/uplus-wss#89]
**Describe the bug**
Insurance team related information is displaying in Communications mobile self service  

**To Reproduce**
1. Go to:  Go to Git hub and point url to https://crmdev84.pegacloud.net/prweb/ in quick links
2. Click on Upgrade device 
3. Will able to see Insurance team related information is displaying in Communications mobile self service

**Expected behavior**
Insurance team related information is not required for Communications. Need to remove that screen or keep comms related info.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Any (Android/IOS)
 - OS: Any (Android/IOS)
 - Browser: Any
 - Version: Any

**Additional context**
![Mobile Self service](https://user-images.githubusercontent.com/54707579/64013410-5752d280-cb3d-11e9-98cd-3e71ec6de47b.jpg)

**Comment by ricmars** [comment]
need to remove the page for all industries except insurance
