### ISSUE TITLE
Parameters not passed to set the details of the user logged in 

### ISSUE THREAD

**Issue by Nishitasuresh** [pegasystems/uplus-wss#9]
In the previous model of wss, we used to set the parameters in the cookie, to set the details of the logged in user (screenshot below).
![image](https://user-images.githubusercontent.com/50484886/57763335-cf2bf700-771e-11e9-8660-1b26667ae818.png)

In the new WSS which is in GitHub,I have tried to pass the same parameters by configuring it as below.
![image](https://user-images.githubusercontent.com/50484886/57763485-12866580-771f-11e9-992e-469983c45051.png)
But the parameters do not seem to be passed.

**Comment by Nishitasuresh** [comment]
The application is Healthcare for payers

**Comment by ricmars** [comment]
You need to use =   ..e.g param1=value1,param2=value2

**Comment by ricmars** [comment]
closing issue - the parameters were set incorrectly in the user settings page
