### ISSUE TITLE
Microsite not redirecting to account page

### ISSUE THREAD

**Issue by Yarramneni-vasavi** [pegasystems/uplus-wss#90]
We are using 'pegaMashupNavigateBack' function in marketing 'userworkform' rule to redirect to the account page. But it is not redirecting and showing a blank screen. 

As per my analysis, we found that 'strDomainsWhiteList' property is not having the github URL value though we mentioned the URL in mashup security section in marketing application rule. and we also observed that 'isWebMashup' value is being set as NULL on the Microsite thread though we are passing its value as 'true' in the URL request. 

[config-text_lab5021.zip](https://github.com/pegasystems/uplus-wss/files/3567871/config-text_lab5021.zip)

Instance details: http://10.225.93.21:9080/prweb
CSHC_mkt/Install@123

1. Login as 'bethamiller74@pegatsdemo.com' in the health_payer portal.
2. Click on the account page offer.
3. Observe that Microsite is launched and try clicking on the accept button.
4. See the blank screen displayed. (screenshot 3)

Expected behavior:
The microsite should redirect to the account page.

Screenshot 1:
![image](https://user-images.githubusercontent.com/10959887/64146666-70100080-ce3b-11e9-9559-c1f22b3759a9.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/10959887/64146264-ef9cd000-ce39-11e9-8a49-dfa6bb037555.png)

Screenshot 3:
![image](https://user-images.githubusercontent.com/10959887/64146282-017e7300-ce3a-11e9-9cc5-b6155bfd1b43.png)

**Comment by ricmars** [comment]
if strDomainsWhiteList is not set - it means that the application in Pega used by the Mashup for the microsite is not correctly setup - closing the issue.
