### ISSUE TITLE
Stage name display problem in mobile browser

### ISSUE THREAD

**Issue by AmulyaElluru** [pegasystems/uplus-wss#92]
**Describe the bug**
When link is opened from a mobile browser the stage name is displayed in white color on grey background.

**To Reproduce**
1. Go to 'https://pegasystems.github.io/uplus-wss/health_payer/' 
2.Upload this json file by clicking on settings  at the bottom.
[config-text_dev.zip](https://github.com/pegasystems/uplus-wss/files/3642246/config-text_dev.zip)
3. Launch this deep linking URL  'https://pegasystems.github.io/uplus-wss/health_payer/index.html?pega_userid=ThomasBrown01@pegatsdemo.com&quicklinkclass=PegaCPMHC-Work-MemberEligibility&IsTriggeredFromMKT=true'
4. Observe the white text on grey BG.

**Expected behavior**
Stage name should be displayed in white color on blue background.
![laptop view](https://user-images.githubusercontent.com/55691694/65428625-55c1b500-de32-11e9-9c93-9c25764a9b14.PNG). This is working fine in when link is opened from laptop but not in mobile.

**Screenshots**
![IMG_20190923_175710 (1)](https://user-images.githubusercontent.com/55691694/65428687-6c680c00-de32-11e9-8d6d-745d41588570.jpg)

**Additional context**
For our case we don't need that stage name on the top when opened from mobile web browser and we need to display other user friendly label instead of stage name when opened from laptop. Is there any possibility to achieve this.

**Comment by ricmars** [comment]
phone for uplus is expected to use a screenflow - closing bug since this is not a uplus WSS issue
