### ISSUE TITLE
When deep link is refreshed, there is an error

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#93]
We have a use case to send a hyperlink in sms and when clicking on the link, we need to open a mashup case in WSS. We are using the deep link url in this format https://fspilot-qa.pegatsdemo.com/uplus-wss/retail_bank/index.html?pega_userid=FSSelfServiceUserDemoEx&quicklinkclass=PegaFS-SCM-Work-OfferRestaurantBooking to achieve it (Using a shortener in sms). When clicking on the link, it resolves to this link https://fspilot-qa.pegatsdemo.com/uplus-wss/retail_bank/quicklink2 and opens the case correctly. But now if we happen to refresh the screen, we get an error as this url standalone is not resolved. This is more pronounced when we open the link from mobile as a swipe is resulting in refresh inadvertently. This results in the apache error resulting in a bad experience during the demo. Is there any way in which this can be avoided?

**Comment by ricmars** [comment]
should be fixed now

**Comment by 7Tushar** [comment]
Hi @ricmars , we took the latest code from github and now though we are not getting  the 404 error, on refreshing the page, it goes back to home page instead of showing the current page. Is this expected?
