### ISSUE TITLE
Option to customize U+ branding for customer demos

### ISSUE THREAD

**Issue by gurus4283** [pegasystems/uplus-wss#94]
Currently, the WSS Github sites are with U+ Bank / U+ Comms branding. I would like to customize it with necessary customer logos and branding.

If I am doing a demo to Bank of America, I would like to showcase this as a self service portal of Bank of America with appropriate logo and branding.

If this isn't there already, this could be helpful. If it is there, please guide me and ignore this request.

**Comment by ricmars** [comment]
please follow these instructions. https://github.com/pegasystems/uplus-wss/wiki/How-to-customize-the-Uplus-application

**Comment by ricmars** [comment]
please reply with comments / feedback on how to update this document.

**Comment by ricmars** [comment]
closing question - see instructions
