### ISSUE TITLE
Skin name is picking wrong for Health care portals

### ISSUE THREAD

**Issue by Yarramneni-vasavi** [pegasystems/uplus-wss#96]
**Describe the bug**
When we are trying to display segmented radio buttons, On click of button we are getting the ‘blue’ color which should ideally be ‘Green’ color in Healthcare layer(Screenshot 1). 

Rootcause:
the root cause for this issue is due to when condition in ‘MashupMainArea.vue’ file, the when condition is set as ‘health’ for health care industry (Screenshot 2) but In health care we have different portals like ‘health_payer’, ‘health_provider’ etc. (Screenshot 3)

and hence it is picking up the ‘ClaritySkin’ only instead of ‘ClaritySkin_Keppel’.

**Expected behavior**
The button on click should display 'Green' colour instead of blue.  

**Screenshots**
Screenshot 1:
![buttonIssue](https://user-images.githubusercontent.com/10959887/67364897-18b22500-f58e-11e9-9fb5-e071da4b7fb0.png)

Screenshot 2:
![2019-10-23 11_47_03-uplus-wss_MashupMainArea vue at 3da4d8bfae1d7fafb675fa90f81a07a351296dc4 · pegas](https://user-images.githubusercontent.com/10959887/67364910-21a2f680-f58e-11e9-9b27-2a347f4167a1.png)

Screenshot 3:
![2019-10-23 11_51_26-](https://user-images.githubusercontent.com/10959887/67364918-28ca0480-f58e-11e9-812c-6539c548c6d4.png)

**Comment by ricmars** [comment]
fixed.
