### ISSUE TITLE
The UI controls and images are not properly displayed

### ISSUE THREAD

**Issue by SureshBabuSabbu** [pegasystems/uplus-wss#97]
**Describe the bug**
In the commercial banking, The UI controls were not displaying properly ex. textarea and dropdown which are not having the borders on all the sides. Attached the screenshot for the same. And also the images and the table content are scattered.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/51121722/67583683-b9107100-f769-11e9-9cac-19cc8b5ad89a.png)
![image](https://user-images.githubusercontent.com/51121722/67583777-de9d7a80-f769-11e9-9085-339d6ca23ae9.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ricmars** [comment]
This is a Clarity Issue - not a Uplus issue

**Comment by ricmars** [comment]
closing issue - BUG-521225 created
