### ISSUE TITLE
Styling issues in Bot

### ISSUE THREAD

**Issue by PreethiBalakrishna** [pegasystems/uplus-wss#98]
**Describe the bug**
In chat bot, The bot icon and question mark for KM articles are not displaying properly. Attached the screenshot for the same.

**To Reproduce**
Issue is also present on local github too
1. Go to http://10.225.93.98:9080/Uplus/retail_bank
2. After chat bot is loaded, login and click on the bot
3. Select 'Yes' in the first question
4. bot icon and question mark for KM article is out of allignment

**Expected behavior**
The bot icon should appear on the top left consistently in all bot messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/57181621/67860786-c8fecb00-fb44-11e9-9e8d-ceeecc6d489f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ricmars** [comment]
chat bot issue - not a WSS issue. closing the bug
