### ISSUE TITLE
Invocation of non microsite url from clickthrough for an offer using mashup gadget

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#99]
We have a use case to open an existing CLM case on click of Learn More of an offer. Since the case is not in Marketing, we do not have a microsite to open for this. So we want to provide a snapstart url in clickthrough field of the offer. But noticed that this does not load the case in a mashup gadget. Instead it gets loaded in an iframe. Due to this when we have actions configured on buttons like open assignment within the flow, they do not work. It works fine when invoked via microsite or quick links as they seem to be loaded within the mashup gadget. Can snapstart urls also be invoked within a mashup gadget instead of iframe.

**Comment by ricmars** [comment]
a snapstart url cannot be invoked inside a mashup - snapstart url and mashup are 2 different ways to open a case.

**Comment by VidyaMenon** [comment]
Basically we need some way to launch a non microsite case from GitHub and it needs to be launched in a mashup gadget. Is there any way to do that?
